#!/usr/bin/env python3
"""
check_C2_transcendental_rank.py — Phase 3 step B: close rank T, and hence rho.

Emits C2_cooper_s{7,10}_v3.json. This is the FIRST artifact in this repo permitted to carry
a non-null picard_rank since E-007 retracted rho=4/T=18, and it is emitted under T0
authorization of 2026-07-26 ("accept, but require a second source first" — condition met,
see refs/literature_provenance.txt).

THE CHAIN
---------
  1. [A, computed here]  rank V = 3, where V is the sub-VHS generated by the holomorphic
     2-form omega. L3 is irreducible, hence the minimal-order annihilator of the period.
     Source: data/certificates/L3_IRREDUCIBLE.json (check_L3_irreducible_minimal.py).
     ** rho is COMPUTED from this file, never typed in. If step A ever reports a different
     rank, the number emitted here changes with it. That is deliberate: E-010's fabrication
     was a hardcoded 19. **

  2. [A, cited]  X_z is PROJECTIVE. A-vS realise both families as complete intersections:
     s7 in the Grassmannian G(2,6) under its Plucker embedding, s10 in P^3 x P^3 under Segre.
     A closed subvariety of projective space is projective. (E-009.)

  3. [A, definitional]  p_g = h^{2,0} = 1, since X_z is a K3 surface.

  4. [B, sourced twice]  T(X) tensor Q is an IRREDUCIBLE rational Hodge structure.
       Zarhin 1983, Thm 1.6(a), p.207: "the Hdg-module V(Y) is simple", for any smooth
         irreducible projective surface over C with p_g = 1. NO genericity hypothesis.
         Zarhin p.200 defines V(Y) as the orthogonal complement of the algebraic-cycle
         lattice A(Y) in H^2(Y,Q) — i.e. exactly T(X) tensor Q — and states
         dim_Q V(Y) = b_2(Y) - rho(Y).
       Huybrechts, Lectures on K3 Surfaces, Lemma 3.2.7 + Lemma 3.3.1: same statement,
         with T(X) = NS(X)^perp, explicitly conditional on X projective.
     Both fetched, hash-pinned and READ (the Zarhin scan has no text layer and was read as
     rendered page images). See refs/literature_provenance.txt.

  5. [formal]  V is contained in T tensor Q. For very general z the Neron-Severi group is
     locally constant (Noether-Lefschetz), so T = NS^perp is a Gauss-Manin-flat sub-Hodge
     structure containing omega; V is generated by omega under Gauss-Manin.

  6. [formal]  V is a NONZERO sub-Hodge-structure of the irreducible T tensor Q, hence
     V = T tensor Q, hence rank T = rank V = 3.

  7. [arithmetic]  rho = b_2 - rank T = 22 - 3 = 19, by Zarhin p.200's dim V(Y) = b_2 - rho
     together with b_2 = 22 for a K3 surface.

TIER: [B]. Steps 1-3 are computed or directly cited; steps 5-7 are formal; step 4 is a
citation to two independent published sources, not a derivation performed in this repo.

CAVEATS THAT MUST TRAVEL WITH rho = 19
--------------------------------------
  * VERY GENERAL MEMBER. rho = 19 is the generic value. It jumps to 20 on a countable dense
    subset of the base (the Noether-Lefschetz locus; singular K3s). It is NOT a statement
    about every fibre. Step 5 is where this enters.
  * PROJECTIVITY IS LOAD-BEARING, not decoration. Huybrechts Example 3.3.2 exhibits a
    non-projective K3 whose NS(X)^perp is reducible. Discharged here by step 2, but any reuse
    of this certificate on a non-projective family is invalid.
  * This says nothing about s18, which has no K3 established.

WHAT IS *NOT* CLAIMED
---------------------
No Kodaira fibre types (E-007: none are derivable from L2). No discriminant — the retracted
value was -3 and nothing here re-derives it; the field stays null. No Mordell-Weil rank.
No physics.

Usage:
  python3 checkers/check_C2_transcendental_rank.py
  python3 checkers/check_C2_transcendental_rank.py --emit
"""

import argparse
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
STEP_A = ROOT / "data" / "certificates" / "L3_IRREDUCIBLE.json"
B2_K3 = 22  # second Betti number of a K3 surface

CITATIONS = {
    "irreducibility_of_T": [
        {
            "source": "Zarhin, 'Hodge groups of K3 surfaces', J. reine angew. Math. 341 (1983) 193-220",
            "statement": "Theorem 1.6(a), p.207: the Hdg-module V(Y) is simple",
            "V_is_T": "p.200: V(Y) := orthogonal complement of the algebraic-cycle lattice A(Y) "
                      "in H^2(Y,Q); dim_Q V(Y) = b_2(Y) - rho(Y)",
            "hypotheses": "Y a smooth irreducible projective surface over C with p_g = 1; "
                          "no genericity hypothesis",
            "local_copy": "docs/literature/zarhin_1983_crelle341.pdf",
            "sha256": "148ce5ce39388d213b4ed6b019e8d7783e21b898f0d164c3191df69a43d73689",
            "read_how": "scan with no text layer; read as rendered page images (pp. 193, 200, 207)",
        },
        {
            "source": "Huybrechts, 'Lectures on K3 Surfaces', CUP 2016",
            "statement": "Lemma 3.2.7 (draft 2.7): the transcendental lattice of a polarizable "
                         "Hodge structure of K3 type is a polarizable irreducible Hodge structure; "
                         "Lemma 3.3.1 (draft 3.1): T(X) = NS(X)^perp, and if X is projective then "
                         "T(X) is polarizable irreducible",
            "minimality": "Definition 3.2.5 (draft 2.5): T is the minimal primitive sub-Hodge "
                          "structure with V^{2,0} = T^{2,0}",
            "counterexample_without_projectivity": "Example 3.3.2 (draft 3.2): for a non-projective "
                                                   "K3, NS(X)^perp need not be irreducible",
            "local_copy": "docs/literature/huybrechts_K3Global.pdf",
            "sha256": "59da72d5807fd05d08ce28ceaf30a030cfc7e52b92e27778d824ac86cb1dd287",
        },
    ],
    "projectivity_of_our_K3": {
        "source": "Almkvist & van Straten, arXiv:2103.08651, 'the three sporadic third order operators'",
        "s7": "K3 = intersection of six hyperplane sections of G(2,6) in its Plucker embedding",
        "s10": "K3 = intersection of four (1,1)-type hyperplane sections in P^3 x P^3 (Segre)",
        "why_it_discharges": "a closed subvariety of projective space is projective",
        "ticket": "E-009",
    },
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--emit", action="store_true", help="write the C2 v3 certificates")
    args = ap.parse_args()

    if not STEP_A.exists():
        print(f"FAIL: step A certificate missing: {STEP_A}")
        return 1
    step_a = json.loads(STEP_A.read_text())

    if step_a.get("verdict") != "L3_IRREDUCIBLE_AND_MINIMAL":
        print(f"FAIL: step A verdict is {step_a.get('verdict')!r}, not L3_IRREDUCIBLE_AND_MINIMAL. "
              f"Nothing is emitted.")
        return 1

    out, failures = [], []
    for res in step_a["results"]:
        name = res["operator"]
        rank_v = res["step4_minimality"]["rank_of_sub_VHS_generated_by_omega"]
        if not res["step4_minimality"]["pass"] or rank_v is None:
            failures.append(f"{name}: step A did not establish rank V")
            continue

        # rho is COMPUTED from the step-A rank. Never typed in. (E-010)
        transcendental_rank = rank_v
        picard_rank = B2_K3 - transcendental_rank

        cert = {
            "checker": "check_C2_transcendental_rank.py",
            "checker_version": "1.0.0",
            "date": "2026-07-26",
            "operator": name,
            "bulk_oeis": res.get("bulk_oeis"),
            "supersedes": "C2_%s_partner_v2.json (RETRACTED, E-007: rho=4/T=18 came from a "
                          "hardcoded components=2)" % name,
            "picard_rank": picard_rank,
            "transcendental_rank": transcendental_rank,
            "b2": B2_K3,
            "how_rho_was_obtained": {
                "formula": "rho = b_2 - rank T = %d - %d = %d" % (B2_K3, transcendental_rank, picard_rank),
                "rank_T_equals_rank_V_because": "T tensor Q is irreducible (step 4) and V is a "
                                                "nonzero sub-Hodge-structure of it (step 5)",
                "rank_V_source": "data/certificates/L3_IRREDUCIBLE.json (read at runtime, not hardcoded)",
                "b2_source": "Zarhin p.200 gives dim V(Y) = b_2(Y) - rho(Y); b_2 = 22 for a K3",
            },
            "tier": "B",
            "tier_reason": "steps 1-3 computed or directly cited; steps 5-7 formal; step 4 is a "
                           "citation to two independent published sources, not re-derived here",
            "premises": {
                "projective": {"status": "discharged", "how": CITATIONS["projectivity_of_our_K3"]},
                "p_g_equals_1": {"status": "discharged", "how": "X is a K3 surface"},
                "very_general_member": {
                    "status": "ASSUMED",
                    "note": "rho = 19 is the generic value; it jumps to 20 on a countable dense "
                            "subset (Noether-Lefschetz locus). NOT a statement about every fibre.",
                },
            },
            "citations": CITATIONS,
            "not_claimed": [
                "no Kodaira fibre types (E-007: none derivable from L2)",
                "discriminant remains null; the retracted value was -3 and nothing here re-derives it",
                "no Mordell-Weil rank",
                "nothing about s18",
            ],
            "discriminant": None,
            "mordell_weil_rank": None,
            "verdict": "C2_v3_DERIVED",
        }
        out.append(cert)
        print(f"  {name:12} rank V = {rank_v}  ->  T = {transcendental_rank}, "
              f"rho = {B2_K3} - {transcendental_rank} = {picard_rank}   [tier B]")

    if failures:
        for f in failures:
            print(f"  FAIL {f}")
        return 1

    if args.emit:
        for cert in out:
            p = ROOT / "data" / "certificates" / f"C2_{cert['operator']}_v3.json"
            p.write_text(json.dumps(cert, indent=2))
            print(f"  wrote {p.relative_to(ROOT)}")
    else:
        print("\n  (dry run — pass --emit to write the certificates)")

    print("\n  caveats that must travel with rho = 19:")
    print("    * VERY GENERAL member; rho jumps to 20 on a countable dense subset")
    print("    * projectivity is load-bearing (Huybrechts Ex. 3.3.2 is a counterexample without it)")
    print("    * tier B — step 4 is cited, not derived here")
    return 0


if __name__ == "__main__":
    sys.exit(main())
