#!/usr/bin/env python3
"""
check_atkin_lehner_vs_disc_form.py -- task A3 (2026-09-21): the open flag
ATKIN_LEHNER_ACTION_UNVERIFIED of check_T3_level_consistency.py.  The earlier spike
(spike_disc_form_vs_atkin_lehner.py) matched COUNTS only, |O(q_A)| = |W(n)| (4 = 4 at
n = 10).  This checker builds the MAP, through the action on periods, and tests it.

OBJECTS
  T_n = U + <2n>, basis (e, f, w), v^2 = 2xy + 2n z^2, period omega(tau) = (1, -n tau^2, tau)
  (check_CM_points_rho20 conventions, imported, not duplicated).
  A = T_n^*/T_n = Z/2n generated by w/2n, q(w/2n) = 1/(2n) mod 2Z.
  O(q_A) = {m mod 2n : m^2 = 1 mod 4n}.  DERIVED here twice: from q(m g) = m^2/(2n), and by
  brute force over all bijective multipliers preserving q on every element (leg O).
  W(n) = Gamma_0(n)* / Gamma_0(n) = {w_Q : Q || n}, w_Q represented by integer matrices
  [[Q a, b], [n c, Q d]] of determinant Q.

THE MAP, THROUGH GEOMETRY (not by counting)
  B(v, omega(tau)) = y - n x tau^2 + 2 n z tau identifies v with a quadratic polynomial in
  tau.  For g = [[A,B],[C,D]], det = Delta > 0, the pullback  P -> (C tau + D)^2 P(g tau) / Delta
  is a linear map phi_g on T_n (x) Q with  B(phi_g v, omega(tau)) (x) Delta = (C tau+D)^2 B(v, omega(g tau)).
  Stage 0 (sympy, symbolic n) verifies symbolically: phi_g preserves v^2; phi_{gh} = phi_h phi_g; for the
  Atkin-Lehner shape phi_g is INTEGRAL with multiplier on A
        m(g) = Q a d + (n/Q) b c = 2 Q a d - 1 = 1 + 2 (n/Q) b c,
  i.e. m = -1 mod 2Q and m = +1 mod 2n/Q -- "-1 on the Q-primary part of A, +1 on the rest",
  with the 2-adic part stated exactly.  This is a DERIVATION, not a citation.  It depends only
  on Q: the map  w_Q -> m_Q  is well defined on W(n) and lands in O(q_A), NOT only in
  O(q_A)/{+-1}.  This is the lift through SO(2,1): det phi_g = +1.
  Fixed points / reflections (the route the task asked for): when the coset w_Q Gamma_0(n)
  contains a trace-0 element g, g is an involution of the upper half plane with fixed point
  tau_g, the primitive v orthogonal to omega(tau_g) is read off the fixed-point polynomial,
  and stage 0 verifies symbolically  phi_g = - r_v  (r_v the reflection in v).  So r_v is an integral isometry
  with multiplier  - m_Q.  Both lifts agree in O(q_A)/{+-1}; they differ by the global sign.
  A trace-0 representative does not always exist (n = 10, Q = 2: none; the coset contains an
  element of order 4 instead; n = 12, Q = 4: no fixed point in H at all) -- the checker decides
  this exactly by a complete residue search and reports it per (n, Q).

LEGS
  0  stage 0, sympy                      exact, symbolic
  O  O(q_A) derivation                   exact, n = 1..N_SWEEP
  W  lattice-level sweep                 exact, n = 1..N_SWEEP, every Q || n
  F  family level, n from the C2 lattice certificate (never typed): fixed points, vectors
     (exact, and recovered from the NUMERICAL tau by CM.vectors_annihilating), reflections,
     multipliers; t and 1/z at the fixed points (Tier B numeric, two precisions), compared
     with the C1 loci and with the t-transformation constants of the Hauptmodul certificates.
  M  monodromy leg: the family's own monodromy generators (check_U1_lattice stage 2, Tier B:
     entries by numerical recognition, then exact), their multiplier on A, and the invariants
     (v^2, div v) of each reflection, compared with leg F.  This is the one leg that touches the
     operator, and the one where a family could have DISAGREED with the lattice arithmetic.

cooper_s10: n comes from C2_cooper_s10_v4_DRAFT.json (DRAFT by T0 ruling) => every s10 output
is ADVISORY, flag LATTICE_CERT_DRAFT.  cooper_s7: C2_cooper_s7_v5.json, LIVE.

NOT ADOPTED / NOT EDITED: T3 is not adopted; check_T3_level_consistency.py is not edited; the
recommendation on the flag is a recommendation to T0.  No Kodaira reading is made anywhere
(CLAUDE.md ledger item 3): the loci are elliptic points of the modular curve and fixed points
of isometries of T_n; nothing is said about fibres.  No physical reading of any kind.

Exit code 0 iff every gate holds.  Controls: test_atkin_lehner_vs_disc_form_controls.py.

Generated-by: Claude (Fable 5.1), Stream 2 | Verified-by: test_atkin_lehner_vs_disc_form_controls.py
Reviewed-by: N
"""
import json
import subprocess
import sys
from fractions import Fraction as F
from math import gcd
from pathlib import Path

import mpmath as mp
import sympy as sp

sys.path.insert(0, str(Path(__file__).resolve().parent))
import check_CM_points_rho20 as CM  # noqa: E402
import check_T3_level_consistency as T3  # noqa: E402
import check_s10_hauptmodul_gamma010star as H10  # noqa: E402

REPO = T3.REPO
CERTS = T3.CERTS
OUT = CERTS / "ATKIN_LEHNER_DISC_FORM.json"
N_SWEEP = 30
A_RANGE = 12               # |a| bound when listing elliptic representatives (family level)
Y_MIN = F(1, 20)           # window for listed fixed points: Im tau >= Y_MIN, |Re tau| <= 1/2
DPS_LO, DPS_HI = 60, 120   # the two precisions of every numeric recognition
T1_CERT = {"cooper_s7": "HAUPTMODUL_S7_GAMMA07PLUS.json",
           "cooper_s10": "HAUPTMODUL_S10_GAMMA010STAR.json"}
HAND_VECTORS_N10 = [(1, -1, 0), (2, -6, 1), (10, -10, -3)]   # orchestrator's, UNVERIFIED input
HAND_MULTIPLIERS_N10 = [1, 11, 19]                           # orchestrator's, UNVERIFIED input

Refused = CM.Refused
log = CM.log


# ------------------------------------------------------------------ stage 0 ----
def stage0():
    n, A, B, C, D, x, y, z, tau = sp.symbols("n A B C D x y z tau")
    out = {}

    def pull(M, v):
        a, b, c, d = M
        P = -n * v[0] * (a * tau + b) ** 2 + 2 * n * v[2] * (a * tau + b) * (c * tau + d) \
            + v[1] * (c * tau + d) ** 2
        co = sp.Poly(sp.expand(P), tau).all_coeffs()
        co = [0] * (3 - len(co)) + co
        return (sp.simplify(-co[0] / n), sp.simplify(co[2]), sp.simplify(co[1] / (2 * n)))

    v = (x, y, z)
    pv = pull((A, B, C, D), v)
    Mform = phi_entries(A, B, C, D, n)
    out["phi_formula_is_the_pullback"] = all(
        sp.simplify(pv[i] - sum(Mform[i][j] * v[j] for j in range(3))) == 0 for i in range(3))
    nrm = lambda u: 2 * u[0] * u[1] + 2 * n * u[2] ** 2
    out["pullback_scales_norm_by_det_squared"] = sp.simplify(
        nrm(pv) - (A * D - B * C) ** 2 * nrm(v)) == 0
    a2, b2, c2, d2 = sp.symbols("a2 b2 c2 d2")
    gh = (A * a2 + B * c2, A * b2 + B * d2, C * a2 + D * c2, C * b2 + D * d2)
    lhs, rhs = pull(gh, v), pull((a2, b2, c2, d2), pv)
    out["phi_gh_equals_phi_h_phi_g"] = all(sp.simplify(l - r) == 0 for l, r in zip(lhs, rhs))
    # Atkin-Lehner shape: A = Q a, C = Q n' c, D = Q d, n = Q n'; det = Q (Q a d - n' b c)
    Q, np_, a, b, c, d = sp.symbols("Q n_p a b c d")
    Msh = phi_entries(Q * a, b, Q * np_ * c, Q * d, Q * np_)
    unit = Q * a * d - np_ * b * c                      # = 1 on the Atkin-Lehner shape; det = Q * unit
    ent = [[sp.expand(sp.cancel(Msh[i][j] / Q)) for j in range(3)] for i in range(3)]   # phi * unit
    out["AL_shape_phi_entries_are_integer_polynomials"] = all(
        e.is_polynomial(Q, np_, a, b, c, d)
        and all(co.is_integer for co in sp.Poly(e, Q, np_, a, b, c, d).coeffs())
        for row in ent for e in row)
    m = sp.expand(ent[2][2])
    out["multiplier_is_Qad_plus_nprime_bc"] = sp.expand(m - (Q * a * d + np_ * b * c)) == 0
    out["m_equals_2Qad_minus_1_on_shape"] = sp.expand(m - (2 * Q * a * d - 1) + (unit - 1)) == 0
    out["m_equals_1_plus_2nprime_bc_on_shape"] = sp.expand(m - (1 + 2 * np_ * b * c) - (unit - 1)) == 0
    # image of w/2n has integer e- and f-components: ent[0][2]/(2n), ent[1][2]/(2n)
    out["image_of_dual_generator_integral_off_w"] = (
        sp.expand(ent[0][2] / (2 * Q * np_) + a * c) == 0 and sp.expand(ent[1][2] / (2 * Q * np_) - b * d) == 0)
    # trace-0 involution: phi_g = - r_v, v = (-C/n, -B, -A/n)
    Dl = -A * A - B * C
    Mi = [[e / Dl for e in row] for row in phi_entries(A, B, C, -A, n)]
    vv = (-C / n, -B, -A / n)
    v2 = sp.simplify(nrm(vv))
    out["fixed_vector_norm_is_minus_2det_over_n"] = sp.simplify(v2 + 2 * Dl / n) == 0
    G = sp.Matrix([[0, 1, 0], [1, 0, 0], [0, 0, 2 * n]])
    V = sp.Matrix(vv)
    R = sp.eye(3) - 2 * V * (G * V).T / v2
    out["trace0_phi_equals_minus_reflection"] = sp.simplify(sp.Matrix(Mi) + R) == sp.zeros(3, 3)
    if not all(out.values()):
        raise Refused("stage0", str(out))
    return {k: bool(val) for k, val in out.items()}


# ---------------------------------------------------------- exact lattice side ----
def phi_entries(A, B, C, D, n):
    """UNNORMALISED pullback matrix (divide by det): rows x', y', z' against columns x, y, z."""
    inv_n = sp.Rational(1, 1) / n if isinstance(n, sp.Basic) else F(1, n)
    return [[A * A, -C * C * inv_n, -2 * A * C],
            [-n * B * B, D * D, 2 * n * B * D],
            [-A * B, C * D * inv_n, A * D + B * C]]


def phi(g, n):
    """Normalised phi_g as a 3x3 Fraction matrix.  Refuses on det <= 0."""
    (A, B), (C, D) = g
    det = A * D - B * C
    if det <= 0:
        raise Refused("det_not_positive", f"det = {det}")
    return [[F(e) / det for e in row] for row in phi_entries(A, B, C, D, n)]


def matvec(M, v):
    return tuple(sum(M[i][j] * v[j] for j in range(3)) for i in range(3))


def matmul(X, Y):
    return [[sum(X[i][k] * Y[k][j] for k in range(3)) for j in range(3)] for i in range(3)]


def det3(M):
    return (M[0][0] * (M[1][1] * M[2][2] - M[1][2] * M[2][1])
            - M[0][1] * (M[1][0] * M[2][2] - M[1][2] * M[2][0])
            + M[0][2] * (M[1][0] * M[2][1] - M[1][1] * M[2][0]))


def integral_isometry(M, n, what="map"):
    """Gate: M integral AND M^T G M = G.  Returns an int matrix.  Clauses:
    `<what>_not_integral`, `<what>_not_isometry`."""
    if any(F(e).denominator != 1 for row in M for e in row):
        raise Refused(f"{what}_not_integral", str([[str(e) for e in row] for row in M]))
    Mi = [[int(e) for e in row] for row in M]
    G = CM.gram_T(n)
    Mt = [[Mi[j][i] for j in range(3)] for i in range(3)]
    if matmul(matmul(Mt, G), Mi) != G:
        raise Refused(f"{what}_not_isometry")
    return Mi


def multiplier(Mi, n):
    """Action on A = Z/2n: M (w/2n) = m (w/2n) mod T_n.  Clause `dual_generator_leaves_coset`."""
    img = matvec(Mi, (F(0), F(0), F(1, 2 * n)))
    if img[0].denominator != 1 or img[1].denominator != 1 or (img[2] * 2 * n).denominator != 1:
        raise Refused("dual_generator_leaves_coset", str(img))
    return int(img[2] * 2 * n) % (2 * n)


def reflection(n, v):
    """r_v as a Fraction matrix (columns = images of e, f, w)."""
    v2 = CM.norm(n, v)
    if v2 == 0:
        raise Refused("isotropic_vector")
    row = CM.pair_row(n, v)
    return [[F(int(i == j)) - F(2 * v[i] * row[j], v2) for j in range(3)] for i in range(3)]


def neg(M):
    return [[-e for e in row] for row in M]


def O_qA(n, mod_factor=4):
    return [m for m in range(2 * n) if (m * m - 1) % (mod_factor * n) == 0]


def O_qA_bruteforce(n):
    """All m mod 2n such that x -> m x is a bijection of Z/2n and q(m x) = q(x) mod 2Z for
    EVERY x, q(x) = x^2/(2n).  No congruence is assumed."""
    N2 = 2 * n
    out = []
    for m in range(N2):
        if len({(m * x) % N2 for x in range(N2)}) != N2:
            continue
        if all((F((m * x) ** 2 - x * x, N2)) % 2 == 0 for x in range(N2)):
            out.append(m)
    return out


def exact_divisors(n):
    return [Q for Q in range(1, n + 1) if n % Q == 0 and gcd(Q, n // Q) == 1]


def al_rep(Q, n):
    """One representative [[Q a, b],[n c, Q d]], det Q, c = 1: Q a d - (n/Q) b = 1."""
    np_ = n // Q
    if gcd(Q, np_) != 1:
        raise Refused("Q_not_exact_divisor", f"Q = {Q}, n = {n}")
    for a in range(1, np_ + 2):
        for d in range(1, np_ + 2):
            if (Q * a * d - 1) % np_ == 0:
                return ((Q * a, (Q * a * d - 1) // np_), (n, Q * d))
    raise Refused("no_AL_representative", f"Q = {Q}, n = {n}")


def mat2mul(g, h):
    return ((g[0][0] * h[0][0] + g[0][1] * h[1][0], g[0][0] * h[0][1] + g[0][1] * h[1][1]),
            (g[1][0] * h[0][0] + g[1][1] * h[1][0], g[1][0] * h[0][1] + g[1][1] * h[1][1]))


def al_type(g, n):
    """Q such that g (after removing the content) has the shape [[Q a, b],[n c, Q d]], det Q,
    Q || n; else None."""
    (A, B), (C, D) = g
    k = gcd(gcd(A, B), gcd(C, D))
    if k == 0:
        return None
    A, B, C, D = A // k, B // k, C // k, D // k
    Q = A * D - B * C
    if Q <= 0 or n % Q or gcd(Q, n // Q) != 1 or A % Q or D % Q or C % n:
        return None
    return Q


def expected_rule(Q, n, sign_swapped=False):
    """The m mod 2n with m = -1 mod 2Q and m = +1 mod 2n/Q (derived in stage 0).  Unique: the
    two moduli have gcd 2 and lcm 2n, and both residues are odd.  sign_swapped is the WRONG
    rule used as a control."""
    s = -1 if sign_swapped else 1
    sol = [m for m in range(2 * n) if (m + s) % (2 * Q) == 0 and (m - s) % (2 * (n // Q)) == 0]
    if len(sol) != 1:
        raise Refused("rule_not_unique", f"Q = {Q}, n = {n}: {sol}")
    return sol[0]


def trace0_residues(Q, n):
    """COMPLETE decision: a trace-0 element [[Q a, b],[n c, -Q a]] of det Q exists iff
    Q a^2 + 1 = 0 mod n/Q for some a mod n/Q (then b c = -(Q a^2 + 1)/(n/Q), take c = 1)."""
    np_ = n // Q
    return [a for a in range(np_) if (Q * a * a + 1) % np_ == 0]


def higher_order_residues(Q, n):
    """Elliptic elements of trace +-Q (only Q = 2: order 4, Q = 3: order 6, since
    trace^2 < 4 Q): Q a (s - a) - 1 = 0 mod n/Q, s = +-1.  Complete residue search."""
    if Q not in (2, 3):
        return []
    np_ = n // Q
    return [(a, s) for s in (1, -1) for a in range(np_) if (Q * a * (s - a) - 1) % np_ == 0]


def fixed_vector(g, n):
    """Primitive v with x > 0 orthogonal to omega(tau_g), from the fixed-point polynomial
    C tau^2 + (D - A) tau - B.  Clause `no_fixed_point_in_H` unless trace^2 < 4 det."""
    (A, B), (C, D) = g
    det, tr = A * D - B * C, A + D
    if tr * tr - 4 * det >= 0 or C == 0:
        raise Refused("no_fixed_point_in_H", f"trace^2 - 4 det = {tr * tr - 4 * det}")
    raw = (F(-C, n), F(-B), F(D - A, 2 * n))
    den = 1
    for e in raw:
        den = den * e.denominator // gcd(den, e.denominator)
    iv = [int(e * den) for e in raw]
    k = gcd(gcd(iv[0], iv[1]), iv[2])
    iv = [e // k for e in iv]
    if iv[0] < 0:
        iv = [-e for e in iv]
    tau = (F(A - D, 2 * C), F(4 * det - tr * tr, 4 * C * C))
    return tuple(iv), tau


def sweep_one(n):
    """Leg W at one n.  Every failure is a Refused with a named clause."""
    Qs = exact_divisors(n)
    Oq = O_qA(n)
    gamma = [((1, 1), (0, 1)), ((1, 0), (n, 1)), ((1 + n, 1), (n, 1)), ((1, -2), (-n, 1 + 2 * n))]
    rows, mult = [], {}
    for Q in Qs:
        g0 = al_rep(Q, n)
        ms = set()
        for g in [g0] + [mat2mul(g0, h) for h in gamma] + [mat2mul(h, g0) for h in gamma]:
            if al_type(g, n) != Q:
                raise Refused("representative_not_AL_shape", f"n={n} Q={Q} {g}")
            Mi = integral_isometry(phi(g, n), n, "phi")
            if det3(Mi) != 1:
                raise Refused("phi_det_not_plus_one", f"n={n} Q={Q}")
            ms.add(multiplier(Mi, n))
        if len(ms) != 1:
            raise Refused("multiplier_depends_on_representative", f"n={n} Q={Q}: {sorted(ms)}")
        m = ms.pop()
        if m not in Oq:
            raise Refused("multiplier_not_in_O_qA", f"n={n} Q={Q} m={m}")
        if m != expected_rule(Q, n):
            raise Refused("rule_mismatch", f"n={n} Q={Q}: m={m}, rule={expected_rule(Q, n)}")
        mult[Q] = m
        row = {"Q": Q, "representative": g0, "multiplier_phi": m}
        res = trace0_residues(Q, n) if Q > 1 else []
        row["trace0_representative_exists"] = bool(res)
        if res:
            a = res[0]
            g = ((Q * a, -(Q * a * a + 1) // (n // Q)), (n, -Q * a))
            v, _ = fixed_vector(g, n)
            Ri = integral_isometry(reflection(n, v), n, "reflection")
            if integral_isometry(phi(g, n), n, "phi") != neg(Ri):
                raise Refused("phi_not_minus_reflection", f"n={n} Q={Q}")
            mr = multiplier(Ri, n)
            if mr != (-m) % (2 * n):
                raise Refused("reflection_multiplier_not_minus_m", f"n={n} Q={Q}")
            row.update({"trace0_element": g, "fixed_vector": v, "v2": CM.norm(n, v),
                        "multiplier_reflection": mr})
        ho = higher_order_residues(Q, n)
        row["order_4_or_6_representative_exists"] = bool(ho)
        row["fixed_point_in_H_exists"] = bool(res or ho) if Q > 1 else None
        rows.append(row)
    # homomorphism, every pair, on actual matrix products
    for Q1 in Qs:
        for Q2 in Qs:
            g = mat2mul(al_rep(Q1, n), al_rep(Q2, n))
            Q3 = al_type(g, n)
            k = gcd(Q1, Q2)
            if Q3 != Q1 * Q2 // (k * k):
                raise Refused("product_not_AL_of_expected_type", f"n={n} {Q1}*{Q2} -> {Q3}")
            Mi = integral_isometry(phi(g, n), n, "phi")
            if Mi != matmul(integral_isometry(phi(al_rep(Q2, n), n), n, "phi"),
                            integral_isometry(phi(al_rep(Q1, n), n), n, "phi")):
                raise Refused("phi_not_antimultiplicative", f"n={n} {Q1},{Q2}")
            if multiplier(Mi, n) != (mult[Q1] * mult[Q2]) % (2 * n) or multiplier(Mi, n) != mult[Q3]:
                raise Refused("not_a_homomorphism", f"n={n} {Q1},{Q2}")
    image = sorted(mult.values())
    kernel_pm = sorted(Q for Q in Qs if mult[Q] in (1, (2 * n - 1) % (2 * n)))
    refl = {r["Q"]: r["multiplier_reflection"] for r in rows if "multiplier_reflection" in r}
    refl_hom_tests = [(Q1, Q2) for Q1 in refl for Q2 in refl if Q1 < Q2
                      and Q1 * Q2 // gcd(Q1, Q2) ** 2 in refl]
    refl_hom_fail = [(Q1, Q2) for Q1, Q2 in refl_hom_tests
                     if (refl[Q1] * refl[Q2]) % (2 * n) != refl[Q1 * Q2 // gcd(Q1, Q2) ** 2]]
    return {"n": n, "exact_divisors": Qs, "O_qA": Oq, "rows": rows,
            "representatives_per_class": 1 + 2 * len(gamma),
            "rule_minus1_mod_2Q_plus1_mod_2n_over_Q_holds": all(mult[Q] == expected_rule(Q, n) for Q in Qs),
            "map_Q_to_m": {str(Q): mult[Q] for Q in Qs},
            "image_equals_O_qA_as_sets": image == Oq,
            "injective_into_O_qA": len(set(image)) == len(Qs),
            "kernel_modulo_pm1": kernel_pm,
            "injective_modulo_pm1": kernel_pm == [1],
            "fricke_maps_to_minus_one": mult[n] == (2 * n - 1) % (2 * n),
            "reflection_lift_pairs_tested": len(refl_hom_tests),
            "reflection_lift_pairs_failing_in_O_qA": len(refl_hom_fail)}


def leg_O(n_max=N_SWEEP):
    bad = [n for n in range(1, n_max + 1) if O_qA_bruteforce(n) != O_qA(n)]
    if bad:
        raise Refused("O_qA_congruence_disagrees_with_bruteforce", str(bad))
    wrong = [n for n in range(1, n_max + 1) if O_qA_bruteforce(n) != O_qA(n, mod_factor=2)]
    return {"n_range": [1, n_max], "congruence_equals_bruteforce_everywhere": True,
            "control_mod_2n_instead_of_4n_disagrees_at": wrong}


# --------------------------------------------------------------- family level ----
def elliptic_elements(Q, n, a_range=A_RANGE, y_min=Y_MIN):
    """Elliptic elements of the coset w_Q Gamma_0(n), entries bounded, fixed point in the
    logged window.  Returns (g, order_in_PGL2) pairs."""
    np_, out = n // Q, []
    for s in ((0,) if Q not in (2, 3) else (0, 1, -1)):
        for a in range(-a_range, a_range + 1):
            d = s - a
            num = Q * a * d - 1                      # = n' b c
            if num % np_:
                continue
            bc = num // np_
            if bc >= 0:
                continue
            for c in range(1, -bc + 1):
                if bc % c:
                    continue
                g = ((Q * a, bc // c), (n * c, Q * d))
                _, (re, im2) = fixed_vector(g, n)
                if im2 >= y_min * y_min and abs(re) <= F(1, 2):
                    out.append((g, 2 if s == 0 else (4 if Q == 2 else 6)))
    return out


def t_and_w(rel, r, tau, dps):
    old = mp.mp.dps
    mp.mp.dps = dps
    try:
        return CM.w_of_tau(rel, r, tau)
    finally:
        mp.mp.dps = old


def tau_mp(re, im2, dps):
    old = mp.mp.dps
    mp.mp.dps = dps + 30
    try:
        return mp.mpc(mp.mpf(re.numerator) / re.denominator,
                      mp.sqrt(mp.mpf(im2.numerator) / im2.denominator))
    finally:
        mp.mp.dps = old


def identify_locus(w_lo, w_hi, loci):
    """1/z against the C1 loci and z = infinity, at both precisions.  Tier B numeric."""
    hits = []
    for name in loci + ["infinity"]:
        target = mp.mpf(0) if name == "infinity" else 1 / mp.mpf(F(name).numerator) * F(name).denominator
        ok = all(abs(w - target) < mp.mpf(10) ** (-(dps - 25)) * (1 + abs(target))
                 for w, dps in ((w_lo, DPS_LO), (w_hi, DPS_HI)))
        if ok:
            hits.append(name)
    return hits[0] if len(hits) == 1 else None


def p2_crosscheck(key, row, t_hi, cert_path=None):
    """Against data/certificates/CM_POINTS_RHO20.json (task P2): at the same z-locus, the same
    (-v^2, div v, D), and the recorded minimal polynomial of t vanishes at the t found here
    (numeric, working precision).  None if the locus is absent from that certificate."""
    cert = json.loads((cert_path or CERTS / "CM_POINTS_RHO20.json").read_text())
    hits = cert["families"][key]["locus_hits"].get(str(row["z_locus"]))
    if not hits:
        return None
    tt = sp.Symbol("t")
    ok = True
    for h in hits:
        coeffs = [int(c) for c in sp.Poly(sp.sympify(h["t_minpoly"]), tt).all_coeffs()]
        val = mp.polyval([mp.mpf(c) for c in coeffs], t_hi)
        ok = ok and abs(val) < mp.mpf(10) ** -(DPS_HI - 30)
        ok = ok and (h["minus_v2"], h["div_v"], h["D"]) == (-row["v2"], row["div_v"], row["D"])
    return bool(ok)


def t_transform_constants(key, n):
    """How t moves under each w_Q.  Fricke: exact eta transformation (H10.fricke_constant,
    recomputed, not read).  n = 10, Q = 2, 5: read from HAUPTMODUL_S10_GAMMA010STAR.json
    (numerical recognition there, Tier B), and the certificate's matrices are required to be
    the ones H10.al_matrix returns."""
    K, r_new = H10.fricke_constant(T3.LEVEL_COORD[n], n)
    if r_new != {d: -e for d, e in T3.LEVEL_COORD[n].items()}:
        raise Refused("fricke_not_anti_invariant")
    out = {n: ("anti", K)}
    if key == "cooper_s10":
        cert = json.loads((CERTS / T1_CERT[key]).read_text())
        if F(cert["fricke_w10"]["constant_K"]) != K:
            raise Refused("t1_cert_fricke_constant_mismatch")
        for Q in (2, 5):
            e = cert["atkin_lehner_numerical"][f"w{Q}"]
            if tuple(map(tuple, e["matrix"])) != H10.al_matrix(Q, n):
                raise Refused("t1_cert_matrix_not_al_matrix", f"w{Q}")
            out[Q] = (e["t_transform"], F(e["constant"]))
    return out


def family(key):
    """All numeric COMPARISONS are made at DPS_HI + 30 working digits: at mpmath's default 15
    digits a difference of 1e-20 rounds to zero and every tolerance below would be vacuous
    (control S6 exercises this)."""
    with mp.workdps(DPS_HI + 30):
        return _family(key)


def _family(key):
    spec = T3.CANDIDATES[key]
    L = T3.lattice_leg(CERTS / spec["lattice_cert"])
    n = L["n_lattice"]
    advisory = spec["lattice_cert_status"] != "LIVE"
    rel, r = CM.relation_for(key, n)
    loci = json.loads((CERTS / CM.LOCI_CERT[key]).read_text())["finite_singular_loci"]
    tconst = t_transform_constants(key, n)
    sw = sweep_one(n)
    points = {}
    for Q in exact_divisors(n):
        if Q == 1:
            continue
        for g, order in elliptic_elements(Q, n):
            v, (re, im2) = fixed_vector(g, n)
            if (re, im2) != CM.tau_exact(n, v):
                raise Refused("fixed_point_disagrees_with_CM_tau", f"{g}")
            rec = points.setdefault(v, {"v": list(v), "tau_re": str(re), "tau_im_squared": str(im2),
                                        "fixed_by": {}, "elements": []})
            rec["fixed_by"].setdefault(f"w{Q}", set()).add(order)
            if len(rec["elements"]) < 2:
                rec["elements"].append({"Q": Q, "g": g, "order": order})
    rows = []
    for v, rec in sorted(points.items(), key=lambda kv: (-CM.norm(n, kv[0]), kv[0])):
        TX = CM.transcendental_lattice(n, v)
        re, im2 = CM.tau_exact(n, v)
        # step (ii) through the CM machinery: the vector is recovered from the NUMERICAL tau
        old = mp.mp.dps
        mp.mp.dps = DPS_LO
        try:
            rec_v = CM.vectors_annihilating(n, tau_mp(re, im2, DPS_LO), max(v[0], 1))
        finally:
            mp.mp.dps = old
        if v not in rec_v:
            raise Refused("vector_not_recovered_from_numerical_tau", str(v))
        v2, dv = CM.norm(n, v), TX["div_v"]
        reflective = (2 * dv) % v2 == 0
        row = {**rec, "v2": v2, "div_v": dv, "T_X_reduced": TX["reduced_form"], "D": TX["D"],
               "fixed_by": {k: sorted(s) for k, s in rec["fixed_by"].items()},
               "reflection_integral": reflective}
        if reflective:
            Ri = integral_isometry(reflection(n, v), n, "reflection")
            row["multiplier_reflection"] = multiplier(Ri, n)
            row["multiplier_minus_reflection"] = (-row["multiplier_reflection"]) % (2 * n)
        for el in rec["elements"]:
            Mi = integral_isometry(phi(el["g"], n), n, "phi")
            if matvec(Mi, v) not in (v, tuple(-e for e in v)):
                raise Refused("phi_does_not_fix_the_vector", f"{el['g']} {v}")
            el["multiplier_phi"] = multiplier(Mi, n)
            el["phi_equals_minus_reflection"] = bool(reflective and Mi == neg(Ri))
            if el["order"] == 4:
                g2 = mat2mul(el["g"], el["g"])
                el["g_squared_is_in_Gamma0_n_up_to_scalar"] = al_type(g2, n) == 1
                el["phi_squared_equals_minus_reflection"] = bool(reflective and matmul(Mi, Mi) == neg(Ri))
            if el["order"] == 2 and not el["phi_equals_minus_reflection"]:
                raise Refused("phi_not_minus_reflection", f"{el['g']}")
            P = Mi
            k = 1
            while P != [[int(i == j) for j in range(3)] for i in range(3)] and k < 13:
                P, k = matmul(P, Mi), k + 1
            el["order_of_phi_on_T"] = k
            el["g"] = [list(x) for x in el["g"]]
        # numerics, Tier B, two precisions
        t_lo, w_lo = t_and_w(rel, r, tau_mp(re, im2, DPS_LO), DPS_LO)
        t_hi, w_hi = t_and_w(rel, r, tau_mp(re, im2, DPS_HI), DPS_HI)
        row["z_locus"] = identify_locus(w_lo, w_hi, loci)
        row["t_numeric"] = mp.nstr(t_hi, 25)
        checks = {}
        for wq, orders in rec["fixed_by"].items():
            kind, c = tconst.get(int(wq[1:]), (None, None))
            if kind == "anti":      # t(g tau) = c / t(tau) and g tau = tau  =>  t^2 = c
                cc = mp.mpf(c.numerator) / c.denominator
                checks[wq] = {"constraint": f"t^2 = {c}", "counted_in_gate": True,
                              "holds": bool(abs(t_lo ** 2 - cc) < mp.mpf(10) ** -(DPS_LO - 25)
                                            and abs(t_hi ** 2 - cc) < mp.mpf(10) ** -(DPS_HI - 25))}
            elif kind == "inv":
                checks[wq] = {"constraint": f"t -> {c} t: no constraint on t at a fixed point "
                                            "(checked instead: closure of the t-set, family level)",
                              "holds": c == 1, "counted_in_gate": False}
        row["t_consistency_with_T1_certificate"] = checks
        row["agrees_with_CM_POINTS_RHO20_certificate"] = p2_crosscheck(key, row, t_hi)
        row["_t_hi"] = t_hi
        rows.append(row)
    # closure: the t-values at the fixed points of one w_Q are permuted by every other w_Q'
    closure = {}
    for Q, (kind, c) in tconst.items():
        if kind != "anti":
            continue
        cc = mp.mpf(c.numerator) / c.denominator
        for Q2 in exact_divisors(n):
            ts = [rw["_t_hi"] for rw in rows if f"w{Q2}" in rw["fixed_by"]]
            if ts:
                closure[f"t-set of w{Q2} fixed points closed under t -> {c}/t (w{Q})"] = all(
                    any(abs(cc / t1 - t2) < mp.mpf(10) ** -(DPS_HI - 30) for t2 in ts) for t1 in ts)
    for rw in rows:
        del rw["_t_hi"]
    scheme = next(e["riemann_scheme"] for e in json.loads(
        (CERTS / "L3_RIEMANN_SCHEME.json").read_text())["results"] if e["operator"] == key)
    for rw in rows:
        exps = scheme.get("oo" if rw["z_locus"] == "infinity" else str(rw["z_locus"]))
        den = 1
        for e in exps or []:
            den = den * F(e).denominator // gcd(den, F(e).denominator)
        rw["exponent_denominator_lcm_from_L3_RIEMANN_SCHEME"] = den if exps else None
        rw["stabiliser_order_found"] = max(o for os_ in rw["fixed_by"].values() for o in os_)
    orders_ok = all(rw["exponent_denominator_lcm_from_L3_RIEMANN_SCHEME"] == rw["stabiliser_order_found"]
                    for rw in rows)
    p2_ok = all(rw["agrees_with_CM_POINTS_RHO20_certificate"] is True for rw in rows)
    # only the constraints that CAN fail are counted (review 2026-09-21): "t -> 1.t" at a fixed
    # point constrains nothing and is recorded, not gated; the gate must be non-vacuous.
    counted = [ch["holds"] for rw in rows for ch in rw["t_consistency_with_T1_certificate"].values()
               if ch["counted_in_gate"]]
    t_ok = len(counted) > 0 and all(counted) and len(closure) > 0 and all(closure.values())
    locus_of = {}
    for rw in rows:
        for wq in rw["fixed_by"]:
            locus_of.setdefault(wq, set()).add(rw["z_locus"])
    return {"candidate": key, "n": n, "lattice_cert": spec["lattice_cert"],
            "lattice_cert_status": spec["lattice_cert_status"], "advisory": advisory,
            "flags": ["LATTICE_CERT_DRAFT"] if advisory else [],
            "group": spec["group"], "sweep": sw, "fixed_points": rows,
            "comparison_working_dps": int(mp.mp.dps),
            "loci_fixed_by": {k: sorted(map(str, s)) for k, s in sorted(locus_of.items())},
            "loci_from_C1_cert": loci,
            "every_listed_fixed_point_is_a_singular_point_of_L3": all(
                rw["z_locus"] is not None for rw in rows),
            "t_transform_constants": {f"w{Q}": [k, str(c)] for Q, (k, c) in tconst.items()},
            "agrees_with_CM_POINTS_RHO20_certificate": p2_ok,
            "stabiliser_orders_match_L3_riemann_scheme": orders_ok,
            "t_closure_checks": closure, "t_constraints_counted_in_gate": len(counted),
            "t_consistent_with_T1_certificate": t_ok}


# -------------------------------------------------------------- monodromy leg ----
def monodromy_leg(key, n, tamper=None):
    """The family's monodromy generators on its orbit lattice (check_U1_lattice, imported):
    multiplier on the discriminant group, basis-independently, and the invariants of each
    reflection.  Tier B (entries of the matrices come from numerical recognition upstream)."""
    import check_U1_lattice as U1
    from sympy.matrices.normalforms import hermite_normal_form
    old = mp.mp.dps
    mp.mp.dps = U1.DPS
    try:
        L2, _ = U1.load_operators(key)
        loci, Ns, _ = U1.stage2_monodromy(key, L2, verbose=False)
    finally:
        mp.mp.dps = old
    N0 = sp.Matrix([[1, 1, 1], [0, 1, 2], [0, 0, 1]])
    gens = {"cusp_z=0": N0, **{f"z={l}": Ns[str(l)] for l in loci}}
    if tamper == "entry":
        k = f"z={loci[0]}"
        gens[k] = gens[k].copy()
        gens[k][0, 1] += 1
    glist = list(gens.values())
    gs = sp.symbols("g11 g12 g13 g22 g23 g33")
    G = sp.Matrix([[gs[0], gs[1], gs[2]], [gs[1], gs[3], gs[4]], [gs[2], gs[4], gs[5]]])
    eqs = [e for M in glist for e in (M.T * G * M - G)]
    sol = sp.solve(eqs, gs, dict=True)
    if len(sol) != 1 or len(G.subs(sol[0]).free_symbols) != 1:
        raise Refused("monodromy_invariant_form_not_unique")
    Gs = G.subs(sol[0])
    Gs = Gs.subs(list(Gs.free_symbols)[0], 1)
    if Gs[1, 1] < 0:
        Gs = -Gs
    vecs = [(N0 - sp.eye(3)).nullspace()[0]]
    for _ in range(10):
        allv = list(vecs) + [M * u for M in glist + [g.inv() for g in glist] for u in vecs]
        Bm = sp.Matrix.hstack(*allv)
        den = sp.lcm([e.q for e in Bm])
        H = hermite_normal_form((Bm * den).applyfunc(sp.Integer)) / sp.Integer(den)
        new = [H[:, j] for j in range(H.shape[1])]
        if len(new) == 3 == len(vecs) and sp.Matrix.hstack(*new) == sp.Matrix.hstack(*vecs):
            break
        vecs = new
    else:
        raise Refused("monodromy_orbit_lattice_not_stable")
    Bm = sp.Matrix.hstack(*vecs)
    Gi = Bm.T * Gs * Bm
    Gi = Gi * sp.lcm([e.q for e in Gi])
    Gi = (Gi / sp.gcd(list(Gi))).applyfunc(sp.Integer)
    if abs(Gi.det()) != 2 * n:
        raise Refused("monodromy_lattice_det_not_2n", f"det = {Gi.det()}, 2n = {2 * n}")
    Ginv = Gi.inv()
    gen = next((Ginv[:, i] for i in range(3) if sp.lcm([e.q for e in Ginv[:, i]]) == 2 * n), None)
    if gen is None:
        raise Refused("monodromy_disc_group_not_cyclic_on_a_dual_basis_vector")
    out = {}
    for name, M in gens.items():
        X = Bm.inv() * M * Bm
        if any(e.q != 1 for e in X) or X.T * Gi * X != Gi:
            raise Refused("monodromy_generator_not_integral_isometry", name)
        ms = [m for m in range(2 * n) if all(e.q == 1 for e in (X * gen - m * gen))]
        if len(ms) != 1:
            raise Refused("monodromy_multiplier_undefined", name)
        rec = {"multiplier_on_A": ms[0], "det": int(X.det())}
        ker = (X + sp.eye(3)).nullspace()
        if len(ker) == 1 and X ** 2 == sp.eye(3):
            u = ker[0] * sp.lcm([e.q for e in ker[0]])
            u = u / sp.gcd(list(u))
            rec.update({"is_reflection": True, "v2": int((u.T * Gi * u)[0, 0]),
                        "div_v": int(sp.gcd(list(Gi * u)))})
        else:
            rec["is_reflection"] = False
        out[name] = rec
    prod = sp.eye(3)
    for M in gens.values():
        prod = prod * (Bm.inv() * M * Bm)
    k, P = 1, prod
    while P != sp.eye(3) and k < 13:
        P, k = P * prod, k + 1
    ms = [m for m in range(2 * n) if all(e.q == 1 for e in (prod * gen - m * gen))]
    out["product_of_the_three"] = {"multiplier_on_A": ms[0], "order": k, "det": int(prod.det())}
    image = sorted({rec["multiplier_on_A"] for rec in out.values()})
    return {"generators": out, "multipliers_seen": image,
            "acts_trivially_on_A_modulo_pm1": all(m in (1, 2 * n - 1) for m in image),
            "gram_equals_lattice_cert_gram": [[int(e) for e in row] for row in Gi.tolist()]
            == json.loads((CERTS / T3.CANDIDATES[key]["lattice_cert"]).read_text())["derived"]["gram_primitive_even"]}


def compare_monodromy_with_fixed_points(fam, mono):
    """Each reflection in the monodromy must have the invariants (v^2, div v, multiplier) of
    the fixed-point reflection found by leg F at the same z-locus.  Clause
    `monodromy_reflection_disagrees_with_fixed_point`."""
    res = {}
    for name, rec in mono["generators"].items():
        if not name.startswith("z="):
            continue
        z = name[2:]
        cand = [(rw["v2"], rw["div_v"], rw.get("multiplier_reflection")) for rw in fam["fixed_points"]
                if rw["z_locus"] == z]
        got = (rec.get("v2"), rec.get("div_v"), rec["multiplier_on_A"])
        res[name] = {"monodromy": list(got), "fixed_point_reflections": sorted(set(cand)),
                     "agree": bool(cand) and all(c == got for c in cand)}
        if not res[name]["agree"]:
            raise Refused("monodromy_reflection_disagrees_with_fixed_point", f"{name}: {res[name]}")
    return res


# ---------------------------------------------------------------- hand estimate ----
def score_hand_estimate(fams, sweeps):
    s10, n = fams["cooper_s10"], fams["cooper_s10"]["n"]
    got = [multiplier(integral_isometry(reflection(n, v), n, "reflection"), n)
           for v in HAND_VECTORS_N10]
    gen = {1}
    while True:
        new = {(a * b) % (2 * n) for a in gen for b in got + [2 * n - 1]} | gen
        if new == gen:
            break
        gen = new
    byv = {tuple(rw["v"]): rw for rw in s10["fixed_points"]}
    third = byv.get(HAND_VECTORS_N10[2])
    clauses = {
        "n = 10: the three vectors give reflection multipliers 1, 11, 19": got == HAND_MULTIPLIERS_N10,
        "n = 10: with -1 they generate all of O(q_A)": sorted(gen) == O_qA(n),
        "O(q_A) at n = 10 is {1, 9, 11, 19}": O_qA(n) == [1, 9, 11, 19],
        "rule: w_Q acts by -1 on the Q-part and +1 on the rest (exactly: -1 mod 2Q, +1 mod 2n/Q), "
        "up to the global sign": all(sw["rule_minus1_mod_2Q_plus1_mod_2n_over_Q_holds"] for sw in sweeps),
        "the map is a group homomorphism compatible with w_2 w_5 = w_10": (
            s10["sweep"]["map_Q_to_m"]["2"] * s10["sweep"]["map_Q_to_m"]["5"]) % (2 * n)
        == s10["sweep"]["map_Q_to_m"]["10"],      # and gated on matrix products in sweep_one
        "the map is injective modulo +-1": all(sw["injective_modulo_pm1"] for sw in sweeps if sw["n"] > 1),
    }
    # NOT part of the orchestrator's estimate ("Which w_Q fixes which locus is NOT estimated -
    # determine it"): this was the builder's own working expectation, kept separate so that its
    # failure is not attributed to anyone else (review 2026-09-21).
    own = {
        "each of the three s10 loci is the fixed point of an Atkin-Lehner INVOLUTION "
        "whose lattice image is the reflection in the listed vector": bool(
            third and any(el["order"] == 2 for el in third["elements"])),
    }
    return {"source": "orchestrator's hand estimate, issued UNVERIFIED",
            "clauses": {k: ("confirmed" if val else "REFUTED") for k, val in clauses.items()},
            "builder_prior_expectation": {
                "source": "builder's own working expectation; NOT in the orchestrator's estimate, "
                          "which left the locus-to-w_Q assignment to be determined",
                "clauses": {k: ("confirmed" if val else "REFUTED") for k, val in own.items()}},
            "determined_which_w_Q_fixes_which_locus": s10["loci_fixed_by"],
            "reflection_multipliers_computed": got}


# ------------------------------------------------------------------------ main ----
def git_head():
    try:
        return subprocess.run(["git", "-C", str(REPO), "rev-parse", "--short", "HEAD"],
                              capture_output=True, text=True).stdout.strip()
    except Exception:
        return "unknown"


NOT_CLAIMED = [
    "that gate T3 is adopted, or that the flag in check_T3_level_consistency.py is closed: that "
    "file is not edited; the recommendation below is addressed to T0",
    "anything certified about T(cooper_s10): C2_cooper_s10_v4_DRAFT.json is DRAFT by T0 ruling; "
    "every s10 row is advisory (LATTICE_CERT_DRAFT)",
    "that the isometries phi_g extend to the K3 lattice with a prescribed action on the "
    "Neron-Severi side: for multipliers other than +-1 that needs surjectivity of "
    "O(M_n) -> O(q), which is model-knowledge (Nikulin 1979, Thm 1.14.2), unfetched, not pinned",
    "that the moduli space of the cooper_s10 family IS X_0(10)*: the Deep Think question stays open",
    "any Kodaira fibre type at any locus (CLAUDE.md ledger item 3)",
    "any statement about the rho = 20 cut (adopted by T0 on 2026-09-21, D7', read narrowly) or any ranking of candidates",
    "any physical reading whatsoever (VISION sec 1.3; Tier C blocked, F5b)",
]


def main():
    log("stage 0 (sympy, symbolic n) ...")
    s0 = stage0()
    for k, val in s0.items():
        log(f"  {k}: {val}")
    lo = leg_O()
    log(f"leg O: O(q_A) congruence = brute force for n = 1..{N_SWEEP}; "
        f"mod-2n control disagrees at {len(lo['control_mod_2n_instead_of_4n_disagrees_at'])} n")
    sweeps = [sweep_one(n) for n in range(1, N_SWEEP + 1)]
    gates = {
        "W_image_equals_O_qA_for_every_n": all(s["image_equals_O_qA_as_sets"] for s in sweeps),
        "W_injective_into_O_qA_for_every_n": all(s["injective_into_O_qA"] for s in sweeps),
        "W_fricke_maps_to_minus_one_for_every_n": all(s["fricke_maps_to_minus_one"] for s in sweeps),
        "W_kernel_modulo_pm1_is_1_and_fricke": all(s["kernel_modulo_pm1"] == sorted({1, s["n"]})
                                                   for s in sweeps),
    }
    no_fix = [(s["n"], r["Q"]) for s in sweeps for r in s["rows"]
              if r["Q"] > 1 and not r["fixed_point_in_H_exists"]]
    no_tr0 = [(s["n"], r["Q"]) for s in sweeps for r in s["rows"]
              if r["Q"] > 1 and not r["trace0_representative_exists"]]
    log(f"leg W: n = 1..{N_SWEEP}: " + ", ".join(f"{k}={v}" for k, v in gates.items()))
    log(f"  (n, Q) with no trace-0 representative (no reflection for w_Q): {no_tr0}")
    log(f"  (n, Q) with no fixed point in H at all: {no_fix}")
    fams, monos, cmp_ = {}, {}, {}
    for key in ("cooper_s7", "cooper_s10"):
        fam = family(key)
        fams[key] = fam
        tag = "  ** ADVISORY: LATTICE_CERT_DRAFT **" if fam["advisory"] else ""
        log(f"\n{key}: n = {fam['n']} ({fam['lattice_cert_status']}){tag}")
        log(f"  W(n) -> O(q_A): {fam['sweep']['map_Q_to_m']}   O(q_A) = {fam['sweep']['O_qA']}")
        for rw in fam["fixed_points"]:
            log(f"  v={tuple(rw['v'])} v2={rw['v2']} div={rw['div_v']} D={rw['D']} fixed_by={rw['fixed_by']} "
                f"refl_mult={rw.get('multiplier_reflection')} z={rw['z_locus']} t={rw['t_numeric'][:12]}")
        log(f"  loci fixed by: {fam['loci_fixed_by']}")
        log(f"  t consistent with T1 certificate: {fam['t_consistent_with_T1_certificate']}")
        monos[key] = monodromy_leg(key, fam["n"])
        cmp_[key] = compare_monodromy_with_fixed_points(fam, monos[key])
        log(f"  monodromy multipliers on A: "
            f"{ {k: v['multiplier_on_A'] for k, v in monos[key]['generators'].items()} }; "
            f"trivial mod +-1: {monos[key]['acts_trivially_on_A_modulo_pm1']}")
    hand = score_hand_estimate(fams, sweeps)
    log("\nhand estimate, scored:")
    for k, val in hand["clauses"].items():
        log(f"  {val:9s} {k}")
    gates.update({
        "F_t_consistent_with_T1_certificates": all(f["t_consistent_with_T1_certificate"] for f in fams.values()),
        "F_stabiliser_orders_match_L3_riemann_scheme": all(
            f["stabiliser_orders_match_L3_riemann_scheme"] for f in fams.values()),
        "F_agrees_with_CM_POINTS_RHO20_certificate": all(
            f["agrees_with_CM_POINTS_RHO20_certificate"] for f in fams.values()),
        "F_every_listed_fixed_point_is_a_singular_point_of_L3": all(
            f["every_listed_fixed_point_is_a_singular_point_of_L3"] for f in fams.values()),
        "M_monodromy_reflections_agree_with_fixed_point_reflections": all(
            c["agree"] for cc in cmp_.values() for c in cc.values()),
    })
    passed = all(gates.values())
    # recorded, NOT a gate (review 2026-09-21): any integral isometry has its multiplier in O(q_A),
    # and image(W) = O(q_A) is already gated, so this cannot fail once the refusal
    # `monodromy_generator_not_integral_isometry` has not fired.
    implied = {"M_product_multiplier_is_in_image_of_W": all(
        m["generators"]["product_of_the_three"]["multiplier_on_A"] in fams[k]["sweep"]["O_qA"]
        for k, m in monos.items())}
    s10m = monos["cooper_s10"]
    cert = {
        "certificate": "ATKIN_LEHNER_DISC_FORM", "checker": Path(__file__).name,
        "date": "2026-09-21", "code_identity": git_head(),
        "status": "RECORD - proposal stage. T3 is NOT adopted. cooper_s10 output is ADVISORY "
                  "(LATTICE_CERT_DRAFT).",
        "stage0_symbolic": s0, "leg_O": lo,
        "leg_W_sweep": {"n_range": [1, N_SWEEP], "per_n": sweeps,
                        "pairs_n_Q_without_trace0_representative": no_tr0,
                        "pairs_n_Q_without_any_fixed_point_in_H": no_fix},
        "families": fams, "monodromy_leg": monos, "monodromy_vs_fixed_points": cmp_,
        "gates": gates, "implied_not_gated": implied, "hand_estimate_scored": hand,
        "pass_orders": {
            "leg_O_and_leg_W": f"PASS({N_SWEEP}) - finite sweep over n = 1..{N_SWEEP}; the rule "
                               "m = -1 mod 2Q, +1 mod 2n/Q itself is symbolic in n (stage 0)",
            "locus_identification_and_t_values": f"PASS({CM.ORDER}) inherited - z is identified through "
                                                 "the relation 1/z = alpha t + beta + gamma/t, fitted "
                                                 f"upstream to q-order {CM.ORDER} (check_CM_points_rho20)",
            "sweep_order": N_SWEEP, "relation_order": CM.ORDER},
        "findings": {
            "map": "w_Q -> multiplier of phi_{w_Q} on A is a group isomorphism W(n) -> O(q_A) for "
                   f"every n in 1..{N_SWEEP} (exact at each n; PASS({N_SWEEP}) as a statement over n); "
                   "Fricke w_n -> -1",
            "sign": "into O(q_A)/{+-1} the map is NOT injective for n > 1: its kernel is {1, w_n}. "
                    "The reflection lift w_Q -> r_v has multiplier -m_Q and is a homomorphism only "
                    "modulo +-1",
            "monodromy_realises": "on the loop side only the multipliers listed in monodromy_leg.*."
                                  "multipliers_seen occur; a loop is matched to an Atkin-Lehner class "
                                  "only modulo +-1 (for s10, 11 = m(w_2) = -m(w_5))",
            "s10_monodromy_acts_nontrivially_on_A_mod_pm1": not s10m["acts_trivially_on_A_modulo_pm1"],
            "s7_monodromy_acts_trivially_on_A_mod_pm1": monos["cooper_s7"]["acts_trivially_on_A_modulo_pm1"],
        },
        "recommendation_to_T0": "NARROW the flag ATKIN_LEHNER_ACTION_UNVERIFIED: the lattice-level "
                                "action is now explicit and exact (isomorphism, not a count). What stays "
                                "open is stated in not_claimed (extension to the Neron-Severi side; "
                                "identification of the moduli space). Not an edit of check_T3.",
        "tier": "B",
        "tier_reason": "stage 0, legs O and W exact; leg F vectors/reflections/multipliers exact, "
                       f"t and 1/z numeric at {DPS_LO} and {DPS_HI} digits; leg M inherits the numerical "
                       "recognition of check_U1_lattice stage 2; s10 lattice certificate DRAFT",
        "numerics": {"dps": [DPS_LO, DPS_HI], "relation_order": CM.ORDER},
        "inputs": {"note": "docs/literature/MANIFEST.md is deliberately NOT pinned here: no number in "
                           "this certificate is computed from it, and it was modified and uncommitted "
                           "in the working tree at emit time. code_identity is the HEAD at emit, which "
                           "predates this checker; the checker and its controls are identified by the "
                           "self-hashes below.",
                   "sha256": {**{k: h for k, h in CM.input_hashes().items()
                                 if k != "docs/literature/MANIFEST.md"},
                              **{f"data/certificates/{f}": CM.sha256_file(CERTS / f)
                                 for f in list(T1_CERT.values()) + ["CM_POINTS_RHO20.json", "L3_RIEMANN_SCHEME.json"]},
                              **{f"checkers/{f}": CM.sha256_file(REPO / "checkers" / f) for f in (
                                  "check_CM_points_rho20.py", "check_T3_level_consistency.py",
                                  "check_s10_hauptmodul_gamma010star.py", "check_U1_lattice.py",
                                  "check_atkin_lehner_vs_disc_form.py",
                                  "test_atkin_lehner_vs_disc_form_controls.py")}}},
        "not_claimed": NOT_CLAIMED,
        "verdict": "AL_ACTION_ON_DISC_FORM_EXPLICIT" if passed else "NOT_ESTABLISHED",
        "verdict_rendered": (f"AL_ACTION_ON_DISC_FORM_EXPLICIT - PASS({N_SWEEP}) over n for legs O and W; "
                             f"PASS({CM.ORDER}) inherited for every z-locus identification"
                             if passed else "NOT_ESTABLISHED"),
        "provenance": "Generated-by: Claude (Fable 5.1), Stream 2 | Verified-by: "
                      "test_atkin_lehner_vs_disc_form_controls.py | Reviewed-by: N",
    }
    log(f"\nVERDICT: {cert['verdict']}")
    if "--emit" in sys.argv:
        OUT.write_text(json.dumps(cert, indent=1, sort_keys=True, default=list) + "\n")
        log(f"certificate: {OUT.relative_to(REPO)}")
    if "--brief" in sys.argv:
        ctl = subprocess.run([sys.executable, str(Path(__file__).with_name(
            "test_atkin_lehner_vs_disc_form_controls.py"))], capture_output=True, text=True)
        tail = [ln for ln in ctl.stdout.splitlines() if "controls behaved as required" in ln]
        render_brief(f"`test_atkin_lehner_vs_disc_form_controls.py`: {tail[0] if tail else 'NO SUMMARY LINE'} "
                     f"(exit code {ctl.returncode}); each control names the clause that fired.")
    return 0 if passed else 1


# ------------------------------------------------------------------------ brief ----
BRIEF = REPO / "briefs" / "STREAM2_ATKIN_LEHNER_DISC_FORM_2026_09_21.md"


def render_brief(controls_line="(controls not run in this invocation)"):
    """The brief is RENDERED from the certificate: numbers are looked up, never typed."""
    c = json.loads(OUT.read_text())
    L = []
    add = L.append
    add("# Stream 2 brief: Atkin-Lehner group versus the discriminant form of T_n = U + <2n> (2026-09-21)")
    add("")
    add("**Status: RECORD, proposal stage.** Gate T3 is not adopted; `check_T3_level_consistency.py` is not "
        "edited; the rho = 20 cut is adopted (T0 D7', 2026-09-21) and read narrowly; nothing is scored or ranked. Every cooper_s10 statement is "
        "**ADVISORY** (flag `LATTICE_CERT_DRAFT`: `C2_cooper_s10_v4_DRAFT.json` is DRAFT by T0 ruling). "
        "This is lattice and modular arithmetic, Tier B at best, with no physical reading of any kind.")
    add("")
    add(f"Rendered from `data/certificates/ATKIN_LEHNER_DISC_FORM.json` by "
        f"`python3 checkers/check_atkin_lehner_vs_disc_form.py --emit --brief`; numbers are looked up in the "
        f"certificate, not typed. Code identity: {c['code_identity']} (HEAD at emit; this checker is "
        f"uncommitted and is identified by its self-hash in `inputs.sha256`). "
        f"Verdict: `{c['verdict_rendered']}`.")
    add("")
    add("**Orders of the finite checks.** Legs O and W: "
        f"{c['pass_orders']['leg_O_and_leg_W']}. Leg F: {c['pass_orders']['locus_identification_and_t_values']}; "
        f"t and 1/z are Tier B numeric at {c['numerics']['dps'][0]} and {c['numerics']['dps'][1]} digits.")
    add("")
    add("## 1. The flag, and what was missing")
    add("")
    add("`ATKIN_LEHNER_ACTION_UNVERIFIED` (cooper_s10, `check_T3_level_consistency.py`) exists because the only "
        "evidence that the extra Atkin-Lehner involutions of Gamma_0(10)* are compatible with T = U + <20> was a "
        "COUNT, |O(q_A)| = |W(n)| (`spike_disc_form_vs_atkin_lehner.py`). Two groups of the same order need "
        "not be related at all. This task builds the map and tests it.")
    add("")
    add("## 2. The map, through the action on periods (derived, not cited)")
    add("")
    add("With omega(tau) = (1, -n tau^2, tau), B(v, omega(tau)) = y - n x tau^2 + 2 n z tau is a quadratic "
        "polynomial in tau. For g = [[A,B],[C,D]] of determinant Delta > 0 the pullback "
        "P -> (C tau + D)^2 P(g tau) / Delta is a linear map phi_g of T_n (x) Q. Stage 0 (sympy, symbolic n):")
    add("")
    for k, val in c["stage0_symbolic"].items():
        add(f"- `{k}`: {val}")
    add("")
    add("Consequences, all exact. (a) phi_g preserves v^2 and phi_{gh} = phi_h phi_g. (b) For the Atkin-Lehner "
        "shape [[Q a, b],[n c, Q d]], det Q, phi_g is an INTEGRAL isometry and acts on A = Z/2n by the multiplier "
        "m = Q a d + (n/Q) b c = 2 Q a d - 1 = 1 + 2 (n/Q) b c: **m = -1 mod 2Q and m = +1 mod 2n/Q**. That is the "
        "rule \"-1 on the Q-part, +1 on the rest\", with the 2-adic part made exact; it depends on Q only. "
        "(c) When the coset w_Q Gamma_0(n) contains a trace-0 element g, with fixed point tau_g and primitive "
        "fixed vector v, then **phi_g = - r_v**: the reflection r_v is integral and has multiplier -m_Q.")
    add("")
    add("**The -1 ambiguity, stated.** -1 acts trivially on the period domain, so the action on the upper half "
        "plane only sees O(T_n)/{+-1}. Two lifts exist: the lift g -> phi_g (determinant +1) lands in O(q_A) "
        "and is a homomorphism; the reflection lift w_Q -> r_v is a homomorphism only modulo +-1 "
        "(controls R5, R6). O(q_A) itself = {m mod 2n : m^2 = 1 mod 4n} is derived from q(m g) = m^2/(2n) mod 2Z "
        f"and re-derived by brute force over all multipliers for n = 1..{c['leg_O']['n_range'][1]} (agreement "
        f"everywhere: {c['leg_O']['congruence_equals_bruteforce_everywhere']}; the variant \"mod 2n\" disagrees "
        f"at n = {c['leg_O']['control_mod_2n_instead_of_4n_disagrees_at']}).")
    add("")
    add(f"## 3. Lattice-level sweep, every n = 1..{c['leg_W_sweep']['n_range'][1]}, every Q || n (exact)")
    add("")
    for k, val in c["gates"].items():
        if k.startswith("W_"):
            add(f"- `{k}`: {val}")
    add("")
    add(f"So w_Q -> m_Q is a group **isomorphism W(n) -> O(q_A)** at every n of the sweep, "
        f"PASS({c['pass_orders']['sweep_order']}) as a statement over n (set equality, not "
        "a count; multiplicativity checked on actual matrix products for every pair, independence of the "
        f"representative checked on {c['leg_W_sweep']['per_n'][0]['representatives_per_class']} representatives "
        "per class), with **Fricke w_n -> -1**. Modulo +-1 the kernel "
        "is {1, w_n}. This matches the source that is read and pinned (Dolgachev 1996 Thm 7.1, "
        "`docs/literature/MANIFEST.md`): the group in that theorem is Gamma_0(n)+, read in this repo as the "
        "extension by the Fricke involution only, and here Fricke "
        "is the one class whose reflection r_v acts on A by +1. Corroboration, read as source in the pinned "
        "text (`docs/literature/dolgachev_1996_mirror_lattice_polarized_k3.txt`, section 7, around lines "
        "1078-1130; located by the reviewer, re-read for this revision): Gamma_0(n)+ is introduced there as "
        "the Fricke modular group, the proof of Thm 7.1 identifies the group with O(U + <2n>)^*, and it uses "
        "the same representation on binary forms as phi_g here. The derivation in section 2 stands on its own; "
        "the passage is corroboration, not the source of any number.")
    add("")
    add(f"Not every w_Q has a reflection. (n, Q) with no trace-0 representative, decided by a complete residue "
        f"search: {[tuple(x) for x in c['leg_W_sweep']['pairs_n_Q_without_trace0_representative']]}. Among them, "
        f"no fixed point in the upper half plane at all: "
        f"{[tuple(x) for x in c['leg_W_sweep']['pairs_n_Q_without_any_fixed_point_in_H']]}. The map phi is defined "
        "for all of them; the fixed-point route is a cross-check where it exists.")
    add("")
    add("## 4. The two families")
    for key in ("cooper_s7", "cooper_s10"):
        f = c["families"][key]
        add("")
        adv = " **ADVISORY - LATTICE_CERT_DRAFT on every row.**" if f["advisory"] else ""
        add(f"**{key}** - n = {f['n']} (from `{f['lattice_cert']}`, {f['lattice_cert_status']}), group "
            f"{f['group']}.{adv}")
        add("")
        add(f"W(n) -> O(q_A): {f['sweep']['map_Q_to_m']}; O(q_A) = {f['sweep']['O_qA']}.")
        add("")
        add("| v | v^2 | div v | D | fixed by (order of the element) | r_v multiplier | phi multiplier | z | "
            "exponent-denominator lcm (L3_RIEMANN_SCHEME) |")
        add("|---|---|---|---|---|---|---|---|---|")
        for rw in f["fixed_points"]:
            fb = ", ".join(f"{k} ({'/'.join(map(str, o))})" for k, o in rw["fixed_by"].items())
            pm = sorted({e["multiplier_phi"] for e in rw["elements"]})
            add(f"| {tuple(rw['v'])} | {rw['v2']} | {rw['div_v']} | {rw['D']} | {fb} | "
                f"{rw.get('multiplier_reflection')} | {pm} | {rw['z_locus']} | "
                f"{rw['exponent_denominator_lcm_from_L3_RIEMANN_SCHEME']} |")
        add("")
        add(f"Which w_Q fixes which locus: {f['loci_fixed_by']}. Window: |a| <= {A_RANGE}, Im tau >= {Y_MIN}, "
            "|Re tau| <= 1/2; the list of fixed points is not claimed complete. Each vector is obtained exactly "
            "from the fixed-point polynomial AND recovered from the numerical tau alone by "
            "`CM.vectors_annihilating`.")
        add(f"t at the fixed points against the Hauptmodul certificate's transformation constants "
            f"{f['t_transform_constants']}: {f['t_consistent_with_T1_certificate']} "
            f"({f['t_constraints_counted_in_gate']} constraints that can fail are counted; a 't -> t' "
            f"transformation constrains nothing at a fixed point and is recorded, not gated; "
            f"z-locus identification PASS({c['pass_orders']['relation_order']}) inherited; "
            f"Tier B numeric, {c['numerics']['dps'][0]} and {c['numerics']['dps'][1]} digits; closure checks: "
            f"{f['t_closure_checks']}). Agreement with `CM_POINTS_RHO20.json` (same (-v^2, div v, D); its "
            f"minimal polynomial of t vanishes at the t found here): {f['agrees_with_CM_POINTS_RHO20_certificate']}. "
            f"Order of the fixing element = lcm of exponent denominators in `L3_RIEMANN_SCHEME.json`: "
            f"{f['stabiliser_orders_match_L3_riemann_scheme']}.")
    add("")
    s10 = c["families"]["cooper_s10"]
    inf = next(rw for rw in s10["fixed_points"] if rw["z_locus"] == "infinity")
    add("Reading of the s10 table (advisory). z = 1/16 is the Fricke fixed point and z = -1/4 is the w_5 fixed "
        "point; both are involutions and phi = -r_v there. **z = infinity is not the fixed point of an "
        f"Atkin-Lehner involution**: v = {tuple(inf['v'])} is fixed by elements of the w_2 coset of order "
        f"{inf['stabiliser_order_found']} (for example g = {inf['elements'][0]['g']}, phi_g of order "
        f"{inf['elements'][0]['order_of_phi_on_T']} on T_10, multiplier {inf['elements'][0]['multiplier_phi']}); "
        f"g^2 lies in Gamma_0(10) up to a scalar ({inf['elements'][0].get('g_squared_is_in_Gamma0_n_up_to_scalar')}) "
        f"and phi_g^2 = -r_v ({inf['elements'][0].get('phi_squared_equals_minus_reflection')}). So the reflection in "
        "that vector (multiplier 19 = -1) belongs to an order-2 elliptic element of Gamma_0(10) itself, and w_2 has "
        "no reflection anywhere (section 3). t is invariant under w_5 in the Hauptmodul certificate, so the w_5 "
        "fixed points carry no constraint on t; what is checked is that their t-set is closed under t -> 1/(16 t).")
    add("")
    add("## 5. Monodromy leg - the one place a family could have disagreed")
    add("")
    add("The family's own monodromy generators (`check_U1_lattice.py` stage 2, imported; entries by numerical "
        "recognition upstream, then exact; Tier B) act on the orbit lattice, whose Gram matrix equals the one in "
        "the lattice certificate. Their multipliers on A, computed basis-independently:")
    add("")
    add("| family | generator | reflection | v^2 | div v | multiplier on A | leg F at the same locus (v^2, div, r_v multiplier) |")
    add("|---|---|---|---|---|---|---|")
    for key in ("cooper_s7", "cooper_s10"):
        tag = " (ADVISORY)" if c["families"][key]["advisory"] else ""
        for name, rec in c["monodromy_leg"][key]["generators"].items():
            cmpv = c["monodromy_vs_fixed_points"][key].get(name, {}).get("fixed_point_reflections", "")
            extra = f"order {rec['order']}" if "order" in rec else rec.get("is_reflection")
            add(f"| {key}{tag} | {name} | {extra} | {rec.get('v2', '')} | {rec.get('div_v', '')} | "
                f"{rec['multiplier_on_A']} | {cmpv} |")
    add("")
    add(f"Every monodromy reflection has the invariants of the fixed-point reflection found independently in "
        f"section 4: {c['gates']['M_monodromy_reflections_agree_with_fixed_point_reflections']}. "
        f"cooper_s7: the monodromy acts on A through +-1: {c['findings']['s7_monodromy_acts_trivially_on_A_mod_pm1']}. "
        f"cooper_s10 (advisory): it does NOT: {c['findings']['s10_monodromy_acts_nontrivially_on_A_mod_pm1']} - "
        "the loop around z = -1/4 acts by 11, and the product of the three loops has order 4 and multiplier 11 = m(w_2). "
        f"Multipliers seen on the loop side: s7 {c['monodromy_leg']['cooper_s7']['multipliers_seen']}, "
        f"s10 {c['monodromy_leg']['cooper_s10']['multipliers_seen']}. For s10 that is an index-2 subgroup of "
        "O(q_A): the loop at the w_5 fixed point acts by 11 = -m(w_5), numerically the same as m(w_2), so the "
        "loop action on A does not separate w_5 from w_2; a loop is matched to an Atkin-Lehner class only "
        "modulo +-1. The remaining values of O(q_A) are reached through the determinant +1 lift phi, not by "
        "any loop. "
        f"(`implied_not_gated`: {c['implied_not_gated']} - recorded, not part of the verdict, since it cannot "
        "fail once the generators are integral isometries.) "
        "Recorded as observed. What it would mean for the Neron-Severi side is not examined (section 8).")
    add("")
    add("## 6. Hand estimate, scored")
    add("")
    add(f"{c['hand_estimate_scored']['source']}.")
    add("")
    add("| clause | outcome |")
    add("|---|---|")
    for k, val in c["hand_estimate_scored"]["clauses"].items():
        add(f"| {k} | {'**REFUTED**' if val == 'REFUTED' else val} |")
    add("")
    add("The refuted clause is a finding, not a defect: modulo +-1 the map has kernel {1, w_n}; the "
        "injective statement is the one into O(q_A).")
    add("")
    bp = c["hand_estimate_scored"]["builder_prior_expectation"]
    add(f"Separately - {bp['source']}:")
    add("")
    add("| builder's expectation | outcome |")
    add("|---|---|")
    for k, val in bp["clauses"].items():
        add(f"| {k} | {'**REFUTED**' if val == 'REFUTED' else val} |")
    add("")
    add("The third s10 vector is the fixed vector of order-4 elements of the w_2 coset (and of an order-2 "
        "element of Gamma_0(10) itself), not of an Atkin-Lehner involution. Determined assignment (advisory): "
        f"{c['hand_estimate_scored']['determined_which_w_Q_fixes_which_locus']}.")
    add("")
    add("## 7. Recommendation to T0 on the flag: **NARROW**, do not simply close")
    add("")
    add(c["recommendation_to_T0"])
    add("")
    add("- What the evidence now supports: the question the flag asked - do the Atkin-Lehner involutions of "
        "composite level act on T_n compatibly with its discriminant form, or do only the counts agree - is "
        "answered at lattice level by an explicit isomorphism (exact), and for cooper_s10 that isomorphism is "
        "consistent with four artifacts produced separately: the t-transformations of "
        "`HAUPTMODUL_S10_GAMMA010STAR.json`, the loci of `CM_POINTS_RHO20.json`, the exponent denominators of "
        "`L3_RIEMANN_SCHEME.json`, and the family's own monodromy.")
    add("- What stays open, and would justify keeping a narrower flag: w_2 and w_5 act on A by 11 and 9, "
        "not by +-1, so they lie outside the group of the pinned Dolgachev theorem (Gamma_0(n)+, read as Fricke "
        "only). That "
        "Gamma_0(10)* is nevertheless the group of z is then a statement about the family that the lattice "
        "T alone does not supply. The `LATTICE_CERT_DRAFT` flag is separate and untouched.")
    add("- This is a recommendation. `check_T3_level_consistency.py` is not edited by this task.")
    add("")
    add("## 8. Not claimed")
    add("")
    for x in c["not_claimed"]:
        add(f"- {x}")
    add("")
    add("## 9. Thought experiment (an analogy for discussion; it carries no claim)")
    add("")
    n10 = s10["n"]
    m_loop = c["monodromy_leg"]["cooper_s10"]["generators"]["z=-1/4"]["multiplier_on_A"]
    fixed_hours = [h for h in range(2 * n10) if (m_loop * h - h) % (2 * n10) == 0]
    shift = sorted({(m_loop * h - h) % (2 * n10) for h in range(2 * n10)} - {0})
    add("Picture a walker who carries a clock with 2n hours - the discriminant group - around a closed path "
        "in the z-line, and compares the clock on return. For n = 7 the clock always comes back as it left, "
        f"whatever the path. For n = {n10} (advisory) a path around z = -1/4 brings it back with every hour h "
        f"replaced by {m_loop} h: the hours {fixed_hours} are untouched, every other hour is moved by {shift}. "
        "Two walkers who compare "
        "only positions on the z-line cannot tell that anything happened; two who compare clocks can. The "
        "count 4 = 4 said that the clock has as many symmetries as there are Atkin-Lehner classes. The present "
        f"computation says less than 'each path produces its own symmetry': walking only ever produces the "
        f"clock symmetries {c['monodromy_leg']['cooper_s10']['multipliers_seen']}, half of the "
        f"{len(s10['sweep']['O_qA'])} available, and a walker cannot tell from the clock alone whether the "
        "path went around the w_5 point or realised w_2 - the two differ by the global sign, which the clock "
        "comparison along a path does not fix. The other two symmetries belong to the algebraic lift phi, "
        "which no path realises. It is a picture of sections 4-5 and nothing more.")
    add("")
    add("## 10. Controls")
    add("")
    add(controls_line + " Real known-bads: tau -> (tau+1)/5 is not an integral isometry (`phi_not_integral`); "
        "level-10 matrices against T_7 and the level-7 Fricke matrix against T_10 (`phi_not_integral`); "
        "cooper_s7 monodromy paired with n = 10 (`monodromy_lattice_det_not_2n`); non-reflective vectors of the "
        "CM table (`reflection_not_integral`); the sign-swapped rule never matches; the hypothesis \"monodromy "
        "acts through +-1\" is true for s7 and false for s10. A defect found while writing the checker is kept "
        "as control S6: at 15 working digits the tolerances are vacuous (a 1e-40 perturbation is accepted); "
        "in the actual process the ambient precision after the imports is higher than 15, and the reviewer's "
        "mutation (wrapper removed) made the t-consistency gate go False, i.e. it fails safe; comparisons run at "
        f"{c['families']['cooper_s10']['comparison_working_dps']} digits.")
    add("")
    add(c["provenance"])
    BRIEF.write_text("\n".join(L) + "\n")
    log(f"brief: {BRIEF.relative_to(REPO)}")


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Refused as e:
        log(f"REFUSED: {e}")
        sys.exit(3)
