#!/usr/bin/env python3
"""
check_L3_irreducible_minimal.py — Phase 3 step A: is L₃ the MINIMAL-order PF operator?

This is the load-bearing computation for the transcendental rank. It replaces the
retracted `check_c2_shioda_tate_v3.py` (ESCALATIONS.md E-010), which hardcoded ρ = 19
and back-solved a Mordell–Weil rank to make the arithmetic close.

WHY MINIMALITY IS THE WHOLE QUESTION
------------------------------------
Let V = the ℚ-sub-VHS of R²π_*ℚ generated by the holomorphic 2-form ω under
Gauss–Manin; rank V = order of the *minimal* operator annihilating the period of ω.
For the very general member X_z of the family, two inclusions pin T(X_z) between them:

  (a) V ⊆ T.  For very general z, NS(X_z) is locally constant (Noether–Lefschetz),
      so T = NS^⊥ is a Gauss–Manin-flat sub-Hodge-structure containing ω. V is
      generated by ω under Gauss–Manin, hence V ⊆ T.  ⇒ rank T ≥ rank V.

  (b) T ⊆ V^sat.  T(X_z)⊗ℚ is by definition the *minimal* primitive sub-Hodge-structure
      of H²(X_z,ℚ) whose complexification contains H^{2,0}. The saturation of V is such
      a sub-Hodge-structure.  ⇒ rank T ≤ rank V.

So rank T = rank V exactly, and ρ = 22 − rank T. Everything therefore reduces to:
**is rank V = 3, i.e. is L₃ minimal?** If L₃ factored, rank V would be 1 or 2 and the
whole ρ/T assignment would move.

WHAT THIS CHECKER SETTLES (computed here, exactly, in ℚ)
--------------------------------------------------------
  Step 1  L₂'s local monodromy at z = 0 is unipotent and ≠ I  ⇒  the monodromy group
          is not contained in the normalizer of a maximal torus  ⇒  NOT DIHEDRAL.
  Step 2  L₂ has no hyperexponential solution (exact residue/exponent obstruction)
          ⇒  L₂ IRREDUCIBLE.
  Step 3  (1) + (2)  ⇒  Sym²(L₂) = L₃ IRREDUCIBLE.
  Step 4  L₃ irreducible ⇒ L₃ is the minimal-order annihilator of *every* nonzero
          solution, in particular of the holomorphic period  ⇒  rank V = 3.

WHAT THIS CHECKER DOES *NOT* SETTLE
------------------------------------
Step 5 — the identification rank T = rank V — is the pair of inclusions (a)/(b) above.
Those are standard Hodge theory (Huybrechts, *Lectures on K3 Surfaces*, CUP 2016, ch. 3
§3.1 for T(X) as the minimal sub-Hodge-structure containing H^{2,0}; ch. 17 §17.1 for the
Noether–Lefschetz locus being a countable union of proper subvarieties). They are NOT
computed here and NOT re-derived here. This checker therefore emits

    picard_rank: null,  transcendental_rank: null

per the standing rule, and reports ρ = 19 only as `conditional_on_step5`. Promoting it
requires a T0 decision that the step-5 citation is accepted — not a further computation
in this repo.

Two further caveats that must travel with any ρ = 19:
  * "very general member". ρ jumps on a countable dense subset of the base (singular K3s
    with ρ = 20). ρ = 19 is the generic value, not a value for every fibre.
  * the family must be the A–vS one (E-009). Existence is settled; this checker assumes it.

Provenance of the operator coefficients: identical to check_L3_riemann_scheme.py, i.e.
lean4_formal_proofs/Structures/CooperSym2Proof.lean (Tier A, kernel-verified), and
independently matched against Almkvist–van Straten arXiv:2103.08651 (E-009).

Usage:
  python3 checkers/check_L3_irreducible_minimal.py
  python3 checkers/check_L3_irreducible_minimal.py --json data/certificates/L3_IRREDUCIBLE.json
"""

import argparse
import json
import sys

import sympy as sp

z, th, s = sp.symbols("z theta s")

# L₂ in the θ-basis: L₂ = P2·θ² + P1·θ + P0,  θ = z·d/dz.
OPERATORS = {
    "cooper_s7": {
        "bulk_oeis": "A183204",
        "P": (-27 * z**2 - 26 * z + 1, -27 * z**2 - 13 * z, -6 * z**2 - 2 * z),
    },
    "cooper_s10": {
        "bulk_oeis": "A005260",
        "P": (-64 * z**2 - 12 * z + 1, -64 * z**2 - 6 * z, -15 * z**2 - z),
    },
}


def theta_to_D(P2, P1, P0):
    """θ = zD, θ² = z²D² + zD  ⇒  L₂ = (P2 z²)D² + (z(P2+P1))D + P0."""
    return sp.expand(P2 * z**2), sp.expand(z * (P2 + P1)), sp.expand(P0)


def exponents_at_zero_and_infinity(P):
    """Indicial roots at z=0 and z=∞, read off the θ-basis directly.

    Writing L₂ = Σ_j z^j R_j(θ), the indicial polynomial at z=0 is R_jmin and at
    z=∞ is R_jmax with the roots negated.
    """
    polys = [sp.Poly(p, z) for p in (P[2], P[1], P[0])]  # ascending in θ
    jmax = max(p.degree() for p in polys)
    R0 = sum(p.nth(0) * th**k for k, p in enumerate(polys))
    Rm = sum(p.nth(jmax) * th**k for k, p in enumerate(polys))
    at_0 = sp.roots(sp.Poly(R0, th))
    at_inf = {-root: mult for root, mult in sp.roots(sp.Poly(Rm, th)).items()}
    return at_0, at_inf


def exponents_at(a2, a1, a0, zc):
    """Indicial roots of a2 y'' + a1 y' + a0 y at the regular singular point z = zc."""
    t = z - zc
    p0 = sp.simplify(sp.limit(t * a1 / a2, z, zc))
    q0 = sp.simplify(sp.limit(t**2 * a0 / a2, z, zc))
    return sorted(sp.solve(sp.Eq(s * (s - 1) + p0 * s + q0, 0), s), key=lambda x: sp.Float(x))


def analyse(name, spec):
    P = spec["P"]
    a2, a1, a0 = theta_to_D(*P)
    at_0, at_inf = exponents_at_zero_and_infinity(P)
    loci = sorted(sp.solve(sp.Eq(P[0], 0), z), key=lambda x: sp.Float(x))
    finite = {str(zc): [str(e) for e in exponents_at(a2, a1, a0, zc)] for zc in loci}

    # ---- Step 1: nontrivial unipotent at z = 0  ⇒  not dihedral -------------------
    # A double indicial root forces a logarithmic second solution (Frobenius), so the
    # local monodromy at 0 is unipotent and ≠ I. Every element of the normalizer N(T)
    # of a maximal torus of SL₂ is either semisimple (in T) or has trace 0 (outside T);
    # a nontrivial unipotent is neither. So the monodromy group is not inside N(T).
    zero_exps = sorted(at_0.items(), key=lambda kv: sp.Float(kv[0]))
    double_root_at_zero = len(at_0) == 1 and list(at_0.values())[0] == 2
    not_dihedral = double_root_at_zero

    # ---- Step 2: no hyperexponential solution  ⇒  L₂ irreducible ------------------
    # If y were hyperexponential, u = y'/y ∈ ℚ̄(z) would be a sum of simple poles with
    # residue = a local exponent at each singular point and a non-negative INTEGER at
    # each ordinary point (the vanishing order of y there). L₂ is Fuchsian, so u has no
    # polynomial part. Hence Σ(residues) lies in the group generated by the finite
    # exponents together with ℤ. The exponent of y at ∞ is −Σ(residues) and must itself
    # be an exponent of L₂ at ∞. Comparing denominators kills it.
    finite_exps = [sp.Rational(e) for exps in finite.values() for e in exps]
    finite_exps += [sp.Rational(e) for e in at_0]
    # smallest N with N·e ∈ ℤ for every attainable residue (ordinary points give ℤ ⊂ this)
    N = sp.ilcm(1, 1, *[sp.Rational(e).q for e in finite_exps])  # ilcm needs >= 2 args
    inf_exps = [sp.Rational(e) for e in at_inf]
    obstructed = [e for e in inf_exps if not (N * e).is_integer]
    no_hyperexp = len(obstructed) == len(inf_exps) and len(inf_exps) > 0
    l2_irreducible = no_hyperexp

    # ---- Steps 3 & 4 --------------------------------------------------------------
    l3_irreducible = bool(l2_irreducible and not_dihedral)
    minimal_order = 3 if l3_irreducible else None

    return {
        "operator": name,
        "bulk_oeis": spec["bulk_oeis"],
        "L2_exponents": {
            "0": [str(e) for e in at_0 for _ in range(at_0[e])],
            **finite,
            "oo": [str(e) for e in at_inf],
        },
        "step1_not_dihedral": {
            "double_indicial_root_at_zero": bool(double_root_at_zero),
            "argument": "double root ⇒ logarithmic solution (Frobenius) ⇒ local monodromy at 0 "
                        "is unipotent and ≠ I; no nontrivial unipotent lies in the normalizer of "
                        "a maximal torus of SL2 (its elements are semisimple or have trace 0)",
            "pass": bool(not_dihedral),
        },
        "step2_L2_irreducible": {
            "attainable_residue_denominator_divides": int(N),
            "exponents_at_infinity": [str(e) for e in inf_exps],
            "obstructed_at_infinity": [str(e) for e in obstructed],
            "argument": f"every attainable Σ(residues) of u=y'/y lies in (1/{N})ℤ, but no exponent "
                        f"of L2 at ∞ does; so no hyperexponential solution exists",
            "pass": bool(l2_irreducible),
        },
        "step3_L3_irreducible": {
            "argument": "Sym² of an irreducible rank-2 system is irreducible unless the monodromy "
                        "is dihedral (contained in the normalizer of a torus), which step 1 excludes",
            "pass": bool(l3_irreducible),
        },
        "step4_minimality": {
            "argument": "an irreducible operator is the minimal-order annihilator of each of its "
                        "nonzero solutions (a lower-order annihilator would give a nontrivial "
                        "gcrd, i.e. a proper right factor)",
            "rank_of_sub_VHS_generated_by_omega": minimal_order,
            "pass": bool(l3_irreducible),
        },
        "step5_hodge_identification": {
            "status": "[B] NOT COMPUTED HERE — standard Hodge theory, cited not re-derived",
            "claim": "rank T(X_z) = rank V for very general z, via V ⊆ T (T is Gauss–Manin-flat "
                     "and contains ω) and T ⊆ V^sat (T is the minimal primitive sub-Hodge-structure "
                     "containing H^{2,0})",
            "citation": "Huybrechts, Lectures on K3 Surfaces, CUP 2016, ch. 3 §3.1 and ch. 17 §17.1",
            "blocks_emission_of_rho": True,
        },
        "conditional_on_step5": {
            "transcendental_rank_T": 3 if l3_irreducible else None,
            "picard_rank_rho": 19 if l3_irreducible else None,
            "caveat": "value for the VERY GENERAL member; ρ jumps to 20 on a countable dense "
                      "subset of the base (singular K3s)",
        },
        # Standing rule (ESCALATIONS.md): emit no ρ and no T until one is derived.
        "picard_rank": None,
        "transcendental_rank": None,
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--json", help="write certificate here")
    args = ap.parse_args()

    results = [analyse(name, spec) for name, spec in OPERATORS.items()]

    for r in results:
        print(f"\n{'='*72}\n{r['operator']}  ({r['bulk_oeis']})\n{'='*72}")
        for pt, ex in r["L2_exponents"].items():
            print(f"  L2 exponents at {pt:>6} : {{{', '.join(ex)}}}")
        print()
        for k in ("step1_not_dihedral", "step2_L2_irreducible",
                  "step3_L3_irreducible", "step4_minimality"):
            print(f"  {'PASS' if r[k]['pass'] else 'FAIL'}  {k}")
        print(f"  ---- rank of sub-VHS generated by ω = "
              f"{r['step4_minimality']['rank_of_sub_VHS_generated_by_omega']}")
        print(f"  [B] step 5 NOT computed here → picard_rank stays null")
        print(f"       conditional_on_step5: T = {r['conditional_on_step5']['transcendental_rank_T']}, "
              f"ρ = {r['conditional_on_step5']['picard_rank_rho']} (very general member)")

    all_pass = all(r["step4_minimality"]["pass"] for r in results)
    cert = {
        "checker": "check_L3_irreducible_minimal.py",
        "checker_version": "1.0.0",
        "date": "2026-07-26",
        "ticket": "Phase 3 step A (supersedes the retracted check_c2_shioda_tate_v3.py, E-010)",
        "results": results,
        "verdict": "L3_IRREDUCIBLE_AND_MINIMAL" if all_pass else "INCONCLUSIVE",
        "picard_rank": None,
        "transcendental_rank": None,
        "emission_blocked_by": "step 5 (Hodge identification) is a citation, not a computation; "
                               "T0 sign-off required before any ρ/T is written to a certificate",
    }
    if args.json:
        with open(args.json, "w") as f:
            json.dump(cert, f, indent=2)
        print(f"\nwrote {args.json}")
    print(f"\nVERDICT: {cert['verdict']}")
    return 0 if all_pass else 1


if __name__ == "__main__":
    sys.exit(main())
