/-!
# Verified Hypergeometric Identity: ∑ k in range (n+1), choose n k = 2^n

This file proves the binomial sum identity using Mathlib's `Nat.sum_range_choose`.
No sorry stubs, no axioms.

Generated by: Creative Telescoping Pipeline
Proof status: CLEAN — zero sorry, zero axiom.
-/

import Mathlib.Data.Nat.Choose.Sum
import Mathlib.Data.Nat.Choose.Basic
import Mathlib.Algebra.BigOperators.Basic

open Nat Finset BigOperators

namespace Nat

/-- The binomial sum identity: ∑ k in range (n+1), choose n k = 2^n.
    Proved directly from Mathlib's `Nat.sum_range_choose`. -/
theorem binomial_sum_equality (n : ℕ) :
    ∑ k in range (n + 1), choose n k = 2^n := by
  exact Nat.sum_range_choose n

end Nat
