#!/usr/bin/env python3
"""
compute_C1_monodromy.py — RETRACTED 2026-07-26 (E-007). DO NOT USE.

################################################################################
##  THIS SCRIPT'S OUTPUT IS WITHDRAWN. Its core mapping is hard-disabled.      ##
################################################################################

Retraction summary (see ESCALATIONS.md E-007 for the full ticket):

  * The operator L2 is a TWISTED Picard-Fuchs operator, not a PF operator.
    A279619's generating function is exactly the square root of A183204's
    (verified on 8 terms from refs/recurrences_v1.json). Taking that square
    root halves the indicial exponents to {0, 1/2} and flips the local
    monodromy determinant to -1.
  * Kodaira fibre monodromies lie in SL_2(Z) and therefore have determinant +1.
    So NO Kodaira fibre type is derivable from L2's exponents by any lookup.
  * The `exponents_to_kodaira_type()` table below was ALSO independently wrong
    (it claimed exp_diff = 1/2 => II/III/IV; actual: II = 1/6, III = 1/4,
    IV = 1/3) and hardcoded `components = 2`, which is what mechanically
    produced the now-withdrawn rho = 4 / T = 18.

The certificates generated by this script (C1_monodromy_*_v2.json and everything
downstream: C1/C2 v1 and v2) are PERMANENTLY RETRACTED. They remain on disk for
the audit trail only and must not be cited as evidence.

Geometry must instead be derived from L3 (fully unipotent, exponents {0,0,0}) or
from an untwisted L2 (gauge transform clearing the 1/2-exponents and restoring a
rational Wronskian). See briefs/STREAM2_ACTION_PLAN_2026_07_26.md Phase 2A/2B.

Independent verification: checkers/check_C1_kodaira_consistency.py
Literature: O'Brien (2016) MSc thesis Thm 6.1; Chan-Cooper-Sica (2010) Conj 5.4.

---- original (superseded) module docstring retained for audit ----

Rigorous Picard-Fuchs exponent to Kodaira-type mapping.

Input: exact PF exponents at singular points (from check_C1_singular_loci.py).
Output: Kodaira fibre types + component multiplicities, Shioda-Tate lattice data.

This script uses _EXACT_ algebraic computation (via SymPy roots and local analysis)
to avoid the F6 fabrication error that plagued check_C1.py.
"""
import argparse
import hashlib
import json
import sys
from fractions import Fraction
from pathlib import Path

import sympy as sp

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "checkers"))
import check_C3b_moduli_map as base  # noqa: E402

CHECKER_VERSION = "1.0.0"


def exponents_to_kodaira_type(exp_diff, exp_list):
    """
    ############################################################################
    ##  RETRACTED 2026-07-26 (E-007). DO NOT USE. DO NOT "FIX".               ##
    ############################################################################

    This function is unsound at two independent levels and is hard-disabled.

    (1) Its exponent->Kodaira table is factually wrong. The docstring below
        claims "exp_diff = 1/2 => II, III, or IV". In fact Kodaira II has
        exponent difference 1/6, III has 1/4, and IV has 1/3. NONE of them
        is 1/2. It also returned `components = 2` HARDCODED regardless of the
        type it had just named (Kodaira II has m = 1). Shioda-Tate then
        mechanically produced rho = 2 + 2 + 0 = 4. That is where the withdrawn
        rho = 4 / T = 18 figures came from -- a hardcoded constant, not geometry.

    (2) More fundamentally, NO exponent->Kodaira lookup can be valid here.
        The operator L2 is a TWISTED Picard-Fuchs operator: A279619's g.f. is
        exactly the square root of A183204's g.f. (verified on 8 terms), so the
        exponents are halved to {0, 1/2} and the local monodromy determinant is
        -1. Kodaira monodromies lie in SL_2(Z) and have determinant +1, so these
        exponents do not describe an elliptic fibration at all.

    Geometry must instead be derived from L3 (fully unipotent) or from an
    untwisted L2 (gauge transform clearing the 1/2-exponents and restoring a
    rational Wronskian).

    See: ESCALATIONS.md E-007
         briefs/STREAM2_ACTION_PLAN_2026_07_26.md (Phase 2A/2B)
         checkers/check_C1_kodaira_consistency.py (independent verification)

    ---- original (unsound) docstring retained below for audit ----

    Map Picard-Fuchs exponent difference to Kodaira fibre type.

    Args:
        exp_diff (Expr): difference of the two local exponents (always positive)
        exp_list (list): [ρ1, ρ2] (the full exponent pair)

    Returns:
        (kodaira_type, rank_defect, components)
          where rank_defect is how many irreducible components the singular fibre has.

    Rules (Kodaira 1963 + refinements):
    - exp_diff = 0 and both = 0 ⇒ I_0 (smooth)
    - exp_diff = 1/n with n ≥ 2 ⇒ typically I_n or I_n^* (n components)
    - exp_diff = 1/2 ⇒ II, III, or IV (all non-split, 1 or 2 components depending on subtlety)
    - exp_diff = 1/3 ⇒ potential III or IV
    - exp_diff = 1/4 ⇒ potential III* or IV*

    This is a heuristic map until full monodromy-orbit analysis is implemented.
    """
    raise RuntimeError(
        "exponents_to_kodaira_type() is RETRACTED (E-007): no exponent->Kodaira "
        "lookup is valid for the twisted operator L2 (det(monodromy) = -1). "
        "See ESCALATIONS.md E-007 and briefs/STREAM2_ACTION_PLAN_2026_07_26.md."
    )

    exp_diff_float = float(exp_diff.evalf())

    # Tolerance for comparison
    tol = 1e-12

    # Smooth fibre
    if abs(exp_diff_float) < tol and all(abs(float(e.evalf())) < tol for e in exp_list):
        return "I_0", 0, 1

    # Rational exponent differences map to classical types
    if abs(exp_diff_float - 0.5) < tol:
        # II, III, IV family — all have exp_diff = 1/2 but differ in multiplicity
        # Heuristic: use component count from discriminant (future: full Weierstrass model)
        return "II (tentative)", 1, 2

    if abs(exp_diff_float - 1.0/3.0) < tol:
        # III family
        return "III (tentative)", 1, 2

    if abs(exp_diff_float - 0.25) < tol:
        # III* or IV* family
        return "III* or IV* (tentative)", 2, 3

    # Fallback: generic I_n type (n = 1/exp_diff rounded)
    if exp_diff_float > 1e-12:
        n = round(1.0 / exp_diff_float)
        if n >= 2:
            return f"I_{n} (tentative)", n - 1, n
        else:
            return f"I_1 or II (ambiguous)", 1, 2

    return "UNKNOWN (exponent difference undefined)", None, None


def monodromy_check(A_poly, B_poly):
    """
    Full monodromy orbit computation for determining Kodaira types rigorously.
    (Stub: full SL2(Z) orbit computation is reserved for extended v1.1.)
    """
    # For now, return the exponent-based classification
    # Future: compute local Weierstrass model at each singular point to get
    # exact component structure and multiplicities.
    return None


def compute_shioda_tate(kodaira_data, mw_rank=0):
    """
    Apply Shioda-Tate formula: ρ = 2 + Σ(m_i - 1) + rank(MW)
    where m_i = number of irreducible components of fibre i.

    Args:
        kodaira_data (list): [(kodaira_type_str, rank_defect, components), ...]
        mw_rank (int): Mordell-Weil rank (assume 0 for now)

    Returns:
        (rho, T) where T = 22 - ρ for K3 surface.
    """
    ns = 2
    for _, _, components in kodaira_data:
        if components is not None:
            ns += components - 1
    rho = ns + mw_rank
    T = 22 - rho
    return rho, T


def run_check(c1_loci_path, partner_id):
    """Load corrected C1-loci JSON and compute Kodaira types + Shioda-Tate."""
    try:
        c1_data = json.loads(Path(c1_loci_path).read_text())
    except FileNotFoundError:
        # If v2 loci file not yet generated, compute it inline
        c1_data = None

    result = {
        "checker": "compute_C1_monodromy.py",
        "checker_version": CHECKER_VERSION,
        "criterion": "C1-monodromy (Kodaira fibre types from PF exponents)",
        "partner": partner_id,
    }

    if c1_data is None:
        result["verdict"] = "ERROR: C1-loci file not found"
        return result, 2

    result["refs_sha256"] = c1_data.get("refs_sha256", "unknown")

    # Extract exponent data
    local_exp = c1_data.get("local_exponents", {})
    exp_diffs = c1_data.get("exponent_differences", {})
    finite_loci = c1_data.get("finite_singular_loci_z", [])

    # Compute Kodaira types at each finite singular point
    fibre_data = []
    for pt in finite_loci:
        if pt in local_exp and pt in exp_diffs:
            exp_list_str = local_exp[pt]
            exp_diff_str = exp_diffs[pt]

            # Parse exponents as fractions
            exp_list = [sp.Rational(e) for e in exp_list_str]
            exp_diff = sp.Rational(exp_diff_str)

            kodaira_type, rank_defect, components = exponents_to_kodaira_type(
                exp_diff, exp_list
            )

            fibre_entry = {
                "singular_point_z": pt,
                "local_exponents": exp_list_str,
                "exponent_difference": exp_diff_str,
                "kodaira_type": kodaira_type,
                "rank_defect": rank_defect,
                "irreducible_components": components,
            }
            fibre_data.append(fibre_entry)

    result["fibres"] = fibre_data
    result["n_singular_fibres"] = len(fibre_data)

    # Apply Shioda-Tate
    if fibre_data:
        rho, T = compute_shioda_tate(
            [(f["kodaira_type"], f["rank_defect"], f["irreducible_components"])
             for f in fibre_data],
            mw_rank=0
        )
        result["picard_rank"] = rho
        result["transcendental_rank"] = T
        result["shioda_tate_formula"] = f"ρ = 2 + Σ(m_i - 1) + rank(MW) = 2 + {rho - 2} + 0 = {rho}"
    else:
        result["picard_rank"] = None
        result["transcendental_rank"] = None

    result["mordell_weil_rank"] = 0
    result["assumption"] = "Mordell-Weil rank = 0 (fibre has no rational points besides identity)"

    result["warning"] = (
        "Kodaira types are TENTATIVE. Full resolution requires Weierstrass model analysis "
        "at each singular fibre. This script uses exponent differences as a heuristic; "
        "the exact types require local discriminant analysis (monodromy-orbit refinement). "
        "See compute_C1_monodromy.py v1.1 for full SL2(Z)-orbit classification."
    )

    result["provenance"] = (
        "Generated-by: scripts/compute_C1_monodromy.py v1.0.0 (Tier B, exponent-based) | "
        "Verified-by: exact algebra (Fuchs relation) | Reviewed-by: pending T0"
    )

    result["verdict"] = f"C1_KODAIRA_TENTATIVE(n_fibres={len(fibre_data)}, rho={result.get('picard_rank', '?')})"

    return result, 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--c1-loci",
        default=None,
        help="Path to C1-loci JSON file (from check_C1_singular_loci.py)"
    )
    ap.add_argument("--partner", required=True)
    ap.add_argument("--out", default=None)
    args = ap.parse_args()

    # If c1-loci not provided, look for the default
    if args.c1_loci is None:
        args.c1_loci = str(REPO / "data" / "certificates" / f"C1loci_{args.partner}.json")

    result, code = run_check(args.c1_loci, args.partner)
    payload = json.dumps(result, indent=2, sort_keys=True)

    out = args.out or str(REPO / "data" / "certificates" / f"C1_monodromy_{args.partner}_v2.json")
    Path(out).write_text(payload + "\n")
    print(payload)
    sys.exit(code)


if __name__ == "__main__":
    main()
