#!/usr/bin/env python3
"""Render the K3_SELECTION_REPORT criterion tables from committed certificates.
Machine-generated output only — no hand-entered numbers (criteria-checkers contract).
Usage: python3 scripts/render_k3_selection_report.py > /tmp/tables.md
"""
import json
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CERT = REPO / "data" / "certificates"
REFS = REPO / "refs" / "recurrences_v1.json"


def j(p):
    return json.loads(Path(p).read_text())


def main():
    refs = j(REFS)["sequences"]

    print("### T1. Candidate register (refs/recurrences_v1.json, frozen)\n")
    print("| id | type | status | source (truncated) |")
    print("|---|---|---|---|")
    for k, v in refs.items():
        status = v.get("_meta_status") or v.get("status") or "OK"
        src = (v.get("source") or "")[:70].replace("|", "/")
        print(f"| {k} | {v.get('type','?')} | {status} | {src} |")

    print("\n### T2. C3b-SYM — symmetric-square structure (constructive, all-n)\n")
    print("| bulk | is Sym²? | op identity L3=Sym²(L2) | partner integral | partner first terms |")
    print("|---|---|---|---|---|")
    for b in ("cooper_s7", "cooper_s10", "domb", "apery_zeta3", "almkvist_zagier_second"):
        p = CERT / f"C3b_symsqrt_{b}.json"
        if not p.exists():
            continue
        c = j(p)
        v = c.get("validation", {})
        isym = v.get("sym2_operator_identity_L3_eq_Sym2L2")
        pl = c.get("partner_L2", {})
        ft = pl.get("first_terms")
        ft = ", ".join(ft[:6]) if ft else "—"
        print(f"| {b} | {'YES' if isym else 'NO'} | {isym} | {pl.get('partner_is_integral')} | {ft} |")

    print("\n### T3. C3b-CAT — catalogued moduli-map relation\n")
    print("| bulk | brane (catalogued) | verdict |")
    print("|---|---|---|")
    for b, brane, label in (("cooper_s7", "apery_zeta2", "A005258"),
                            ("cooper_s10", "apery_zeta2", "A005258"),
                            ("domb", "zagier_sporadic_A", "A002893")):
        p = CERT / f"C3b_{b}__{brane}.json"
        if p.exists():
            c = j(p)
            print(f"| {b} | {brane} ({label}) | {c.get('verdict','?')[:70]} |")

    print("\n### T4. C1 — Kodaira fibre classification (order-2 partners)\n")
    print("| partner | fibres | types | singular points z | exponents |")
    print("|---|---|---|---|---|")
    for p in ("cooper_s7_partner", "cooper_s10_partner"):
        c = j(CERT / f"C1_{p}.json")
        fib = c["fibre_configuration"]["fibres"]
        types = "+".join(f["kodaira_type"] for f in fib)
        pts = ", ".join(f["singular_point_z"] for f in fib)
        exps = "; ".join("(" + ",".join(f["exponents"]) + ")" for f in fib)
        print(f"| {p} | {len(fib)} | {types} | {pts} | {exps} |")

    print("\n### T5. C2 — Picard / transcendental lattice (Shioda–Tate)\n")
    print("| partner | ρ | T=22−ρ | fibre contrib | MW rank (assumed) | disc (placeholder) |")
    print("|---|---|---|---|---|---|")
    for p in ("cooper_s7_partner", "cooper_s10_partner"):
        c = j(CERT / f"C2_{p}.json")
        L = c["lattice"]
        print(f"| {p} | {L['picard_number']} | {L['transcendental_rank']} "
              f"| {L['fibre_contribution']} | {L['mordell_weil_rank']} "
              f"| {L['lattice_discriminant']} |")

    print("\n### T6. Min-ODE-order discriminator (new checker, 2026-07-24)\n")
    print("| sequence | min ODE order | min recurrence order | verdict |")
    print("|---|---|---|---|")
    for sid in ("A112019",):
        p = CERT / f"MINODE_{sid}.json"
        if p.exists():
            c = j(p)
            print(f"| {sid} | {c['min_ode']['order']} | {c['min_recurrence']['order']} "
                  f"| {c['verdict'][:80]} |")

    print("\n*(machine-generated by scripts/render_k3_selection_report.py — do not hand-edit)*")


if __name__ == "__main__":
    main()
